### ISSUE TITLE
Wrong Parameter

### ISSUE THREAD

**Issue by xR4E** [aliparlakci/bulk-downloader-for-reddit#102]
Tried to run the software a second time and save to the same folder as before (same sub reddit)

Here's what happened:

EERROR:root:OSError
Traceback (most recent call last):
  File "C:\Users\Ali\AppData\Roaming\Python\Python37\site-packages\cx_Freeze\initscripts\__startup__.py", line 40, in run
  File "C:\Users\Ali\AppData\Roaming\Python\Python37\site-packages\cx_Freeze\initscripts\Console.py", line 37, in run
  File "script.py", line 725, in <module>
  File "script.py", line 714, in main
  File "script.py", line 583, in download
  File "D:\projects\bulk-downloader-for-reddit\src\utils.py", line 107, in printToFile
OSError: [WinError 87] Falscher Parameter

**Comment by aliparlakci** [comment]
Can you provide the CONSOLE_LOG.txt file? It is inside the download directory in LOG_FILES.

**Comment by xR4E** [comment]
Thats basically the thing that let to the error:


(133/984) – gtmbnw – r/gonewild – DIRECT
yourlittlecutie_[F]_You_asked_to_see_my_boobs,_I_hope_you_like_them_as_much_as_I_do_🥺🥰
It already exists

(134/984) – gtmbgs – r/gonewild – DIRECTERROR:root:OSError
Traceback (most recent call last):
  File "C:\Users\Ali\AppData\Roaming\Python\Python37\site-packages\cx_Freeze\initscripts\__startup__.py", line 40, in run
  File "C:\Users\Ali\AppData\Roaming\Python\Python37\site-packages\cx_Freeze\initscripts\Console.py", line 37, in run
  File "script.py", line 725, in <module>
  File "script.py", line 714, in main
  File "script.py", line 583, in download
  File "D:\projects\bulk-downloader-for-reddit\src\utils.py", line 107, in printToFile
OSError: [WinError 87] Falscher Parameter


Is it because the name is too long?!

**Comment by aliparlakci** [comment]
Does this error recur? I did not quite understand why it happens by I will release a new version where I completely changed that line in couple of days. Most probably your issue will be gone. Nevertheless, I will be investigating it.

Btw, it did not raised any when I try to download it in my computer.

Thanks for the feedback!
