### ISSUE TITLE
"self" doesn't work as an option for --skip

### ISSUE THREAD

**Issue by shinji257** [aliparlakci/bulk-downloader-for-reddit#132]
System: Windows 10 (so I'm using the binary)
Version: 1.9.1

When attempting to use `--skip self` it doesn't work and throws a KeyError in the logs.

Log Excerpt:
```
(1/211) — hiwmqu — r/24hoursupport — u/RecklessMe —  – DIRECT
KeyError: 'self'
See CONSOLE_LOG.txt for more information
ERROR:root:KeyError
Traceback (most recent call last):
  File "C:\Users\Ali\AppData\Local\Programs\Python\Python38\lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 40, in run
  File "C:\Users\Ali\AppData\Local\Programs\Python\Python38\lib\site-packages\cx_Freeze\initscripts\Console.py", line 37, in run
  File "script.py", line 351, in <module>
  File "script.py", line 337, in main
  File "script.py", line 155, in download
  File "script.py", line 95, in downloadPost
  File "D:\projects\bulk-downloader-for-reddit\src\downloaders\Direct.py", line 17, in __init__
  File "D:\projects\bulk-downloader-for-reddit\src\downloaders\downloaderUtils.py", line 47, in getFile
KeyError: 'self'
```

**Comment by shinji257** [comment]
Closing since PR is merged.
