### ISSUE TITLE
Bug: 😂 Emoji in Filename causes fatal error

### ISSUE THREAD

**Issue by redpoptarts** [aliparlakci/bulk-downloader-for-reddit#158]
Downloading a file that contains an emoji causes the program to crash.
I attempted to download a user that has a post whose filename contains a '😂'.

I'm not sure if it fails on the print-to-screen step or the file-creation step. (There was no way to silence screen logging)  Here is the CONSOLE_LOG.txt file:

```
UnicodeEncodeError: 'charmap' codec can't encode character '\U0001f602' in position 57: character maps to <undefined>
See CONSOLE_LOG.txt for more information
ERROR:root:UnicodeEncodeError
Traceback (most recent call last):
  File "C:\Users\Ali\AppData\Local\Programs\Python\Python38\lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 40, in run
  File "C:\Users\Ali\AppData\Local\Programs\Python\Python38\lib\site-packages\cx_Freeze\initscripts\Console.py", line 37, in run
  File "script.py", line 351, in <module>
  File "script.py", line 337, in main
  File "script.py", line 155, in download
  File "script.py", line 95, in downloadPost
  File "D:\projects\bulk-downloader-for-reddit\src\downloaders\Direct.py", line 17, in __init__
  File "D:\projects\bulk-downloader-for-reddit\src\downloaders\downloaderUtils.py", line 74, in getFile
  File "D:\projects\bulk-downloader-for-reddit\src\utils.py", line 56, in printToFile
  File "C:\Users\Ali\AppData\Local\Programs\Python\Python38\lib\encodings\cp1252.py", line 19, in encode
UnicodeEncodeError: 'charmap' codec can't encode character '\U0001f602' in position 57: character maps to <undefined>
```

If it's a problem with creating the file, maybe the solution is enabling `utf-8`.
https://stackoverflow.com/questions/27092833/unicodeencodeerror-charmap-codec-cant-encode-characters

**Comment by Symbiomatrix** [comment]
It's probably a good idea to run the entire filename creation process (or rather its title section) through a fitting function, similar to utils' namecorrector - shorten before adding other sections, pass it through ftfy or limit to alphanumeric ascii only with an underline placeholder. If I recall, there wasn't a standardised call to one in the various modules.

**Comment by redpoptarts** [comment]
> It's probably a good idea to run the entire filename creation process (or rather its title section) through a fitting function, similar to utils' namecorrector - shorten before adding other sections, pass it through ftfy or limit to alphanumeric ascii only with an underline placeholder. If I recall, there wasn't a standardised call to one in the various modules.

Honestly that would be appreciated as well.  When I try to back up the resulting files with Dropbox, many of these files contain invalid characters, and cause dropbox to crash.  Being able to autocorrect these on download would certainly help me out in that regard as well.
