### ISSUE TITLE
No connection adapters found

### ISSUE THREAD

**Issue by PotatoLord73** [aliparlakci/bulk-downloader-for-reddit#198]
I have figured out how to run the program, however when it reaches a reddit gallery it gives the error: InvalidSchema: No connection adapters were found, See CONSOLE_LOG.txt for more information
The Console Log does not seem to have any information that can help. Any advice?

**Comment by Serene-Arc** [comment]
This is indicative of a programming error with one of the networking sections of the program. One of the connection protocols has gotten messed up somehow, can you post the logs? It depends on where in the execution the error occurred.

**Comment by PotatoLord73** [comment]
```
InvalidSchema: No connection adapters were found for "['https://i.redd.it/ho82qwkzdrl61.jpg', 'https://i.redd.it/b662j1jzdrl61.jpg']"
See CONSOLE_LOG.txt for more information
ERROR:root:InvalidSchema
Traceback (most recent call last):
  File "F:\bulk-downloader-for-reddit-master\bulk-downloader-for-reddit-master\script.py", line 361, in <module>
    main()
  File "F:\bulk-downloader-for-reddit-master\bulk-downloader-for-reddit-master\script.py", line 346, in main
    download(posts)
  File "F:\bulk-downloader-for-reddit-master\bulk-downloader-for-reddit-master\script.py", line 156, in download
    downloadPost(details, directory)
  File "F:\bulk-downloader-for-reddit-master\bulk-downloader-for-reddit-master\script.py", line 96, in downloadPost
    downloaders[SUBMISSION['TYPE']](directory, SUBMISSION)
  File "F:\bulk-downloader-for-reddit-master\bulk-downloader-for-reddit-master\src\downloaders\gallery.py", line 16, in __init__
    self.rawData = self.getData(link)
  File "F:\bulk-downloader-for-reddit-master\bulk-downloader-for-reddit-master\src\downloaders\gallery.py", line 44, in getData
    res = requests.get(link, headers=headers)
  File "C:\Users\Owen\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "C:\Users\Owen\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\Owen\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\Owen\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\sessions.py", line 649, in send
    adapter = self.get_adapter(url=request.url)
  File "C:\Users\Owen\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\sessions.py", line 742, in get_adapter
    raise InvalidSchema("No connection adapters were found for {!r}".format(url))
requests.exceptions.InvalidSchema: No connection adapters were found for "['https://i.redd.it/d04nwxlay0m61.jpg', 'https://i.redd.it/2gt2wayay0m61.jpg', 'https://i.redd.it/tulbeyqay0m61.jpg', 'https://i.redd.it/wm9m0tvay0m61.jpg', 'https://i.redd.it/vmxsw5tay0m61.jpg', 'https://i.redd.it/4mrvqkoay0m61.jpg']"
ERROR:root:InvalidSchema
Traceback (most recent call last):
  File "F:\bulk-downloader-for-reddit-master\bulk-downloader-for-reddit-master\script.py", line 361, in <module>
    main()
  File "F:\bulk-downloader-for-reddit-master\bulk-downloader-for-reddit-master\script.py", line 346, in main
    download(posts)
  File "F:\bulk-downloader-for-reddit-master\bulk-downloader-for-reddit-master\script.py", line 156, in download
    downloadPost(details, directory)
  File "F:\bulk-downloader-for-reddit-master\bulk-downloader-for-reddit-master\script.py", line 96, in downloadPost
    downloaders[SUBMISSION['TYPE']](directory, SUBMISSION)
  File "F:\bulk-downloader-for-reddit-master\bulk-downloader-for-reddit-master\src\downloaders\gallery.py", line 16, in __init__
    self.rawData = self.getData(link)
  File "F:\bulk-downloader-for-reddit-master\bulk-downloader-for-reddit-master\src\downloaders\gallery.py", line 44, in getData
    res = requests.get(link, headers=headers)
  File "C:\Users\Owen\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "C:\Users\Owen\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\Owen\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\Owen\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\sessions.py", line 649, in send
    adapter = self.get_adapter(url=request.url)
  File "C:\Users\Owen\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\sessions.py", line 742, in get_adapter
    raise InvalidSchema("No connection adapters were found for {!r}".format(url))
requests.exceptions.InvalidSchema: No connection adapters were found for "['https://i.redd.it/ho82qwkzdrl61.jpg', 'https://i.redd.it/b662j1jzdrl61.jpg']"
```
I think that this is it? If not let me know.

**Comment by Serene-Arc** [comment]
Presumably this bug will be moot when the v2 update is released, but the cause of this is that a list is being passed internally instead of the contents of that list. How are you inputting those URLs?

**Comment by PotatoLord73** [comment]
I'm not sure what you mean, I did not input any URLs. I just used the program according to the instructions in the README.

**Comment by Serene-Arc** [comment]
Well I'm hesitant to go through much trouble to find the source of this bug since all this code has been rewritten anyway in the upcoming update so this shouldn't happen when that's released at least. What is contained in the CONSOLE_LOG.txt?

**Comment by PotatoLord73** [comment]
Just the subreddit, time, and limit I sorted by. Followed by the posts downloading and the error message I posted above.
