### ISSUE TITLE
V2: Error thrown when attempting to download Saved entry that is a comment. 

### ISSUE THREAD

**Issue by BlipRanger** [aliparlakci/bulk-downloader-for-reddit#207]
If the Saved entry is actually a comment and not a post, this error is thrown since the "Comment" model in PRAW doesn't have a URL attribute: 
`[2021-03-23 15:06:21,916 - root - ERROR] - Downloader exited unexpectedly
Traceback (most recent call last):
  File "/bdfr/bulkredditdownloader/__main__.py", line 61, in cli_download
    reddit_downloader.download()
  File "/bdfr/bulkredditdownloader/downloader.py", line 316, in download
    self._download_submission(submission)
  File "/bdfr/bulkredditdownloader/downloader.py", line 319, in _download_submission
    if not self.download_filter.check_url(submission.url):
  File "/usr/local/lib/python3.9/site-packages/praw/models/reddit/base.py", line 36, in __getattr__
    raise AttributeError(
AttributeError: 'Comment' object has no attribute 'url'
`

**Comment by BlipRanger** [comment]
Any chance in the future we can grab non-submissions rather than filter them? I know a lot of people save comments as well as posts.

**Comment by Serene-Arc** [comment]
@BlipRanger Saving comments is the domain of the `archive` command. The `download` command is solely for downloading linked data for posts.

**Comment by BlipRanger** [comment]
> 
> 
> @BlipRanger Saving comments is the domain of the `archive` command. The `download` command is solely for downloading linked data for posts.

Ah yeah, makes sense. So if someone runs both archive and download against saved, they should get all saved comments and media (and comments on that media), correct?

**Comment by Serene-Arc** [comment]
Uhhhh good question, I think it should but to be safe I'll reopen this and add some test cases.

**Comment by BlipRanger** [comment]
> Uhhhh good question, I think it should but to be safe I'll reopen this and add some test cases.

`AttributeError: 'Comment' object has no attribute 'title'
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/bdfr/bulkredditdownloader/__main__.py", line 107, in <module>
    cli()
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/bdfr/bulkredditdownloader/__main__.py", line 81, in cli_archive
    reddit_archiver.download()
  File "/bdfr/bulkredditdownloader/archiver.py", line 28, in download
    self._write_submission(submission)
  File "/bdfr/bulkredditdownloader/archiver.py", line 33, in _write_submission
    self._write_submission_json(archive_entry)
  File "/bdfr/bulkredditdownloader/archiver.py", line 44, in _write_submission_json
    file_path = self.file_name_formatter.format_path(resource, self.download_directory)
  File "/bdfr/bulkredditdownloader/file_name_formatter.py", line 52, in format_path
    subfolder = destination_directory / self._format_name(resource.source_submission, self.directory_format_string)
  File "/bdfr/bulkredditdownloader/file_name_formatter.py", line 30, in _format_name
    'title': submission.title,
  File "/usr/local/lib/python3.9/site-packages/praw/models/reddit/base.py", line 36, in __getattr__
    raise AttributeError(
AttributeError: 'Comment' object has no attribute 'title'
`
I can confirm that you get the same sort of error as above (except for title, not url) if you attempt to run archive against a saved list that contains comments. (python3 -m bulkredditdownloader archive --user me --saved --authenticate -L 25  posts)

**Comment by Serene-Arc** [comment]
Thanks, I'll fix this this soon
