### ISSUE TITLE
V2: Unable to run setup.py

### ISSUE THREAD

**Issue by koeningyou** [aliparlakci/bulk-downloader-for-reddit#218]
Hi,

I'm unable to run BDFRv2 setup. I get the error below when running "python3 setup.py";

```
ERROR:root:Error parsing
Traceback (most recent call last):
  File "/home/XXXX/Downloads/bulk-downloader-for-reddit-2/.eggs/pbr-5.5.1-py3.8.egg/pbr/core.py", line 96, in pbr
    attrs = util.cfg_to_args(path, dist.script_args)
  File "/home/XXXX/Downloads/bulk-downloader-for-reddit-2/.eggs/pbr-5.5.1-py3.8.egg/pbr/util.py", line 271, in cfg_to_args
    pbr.hooks.setup_hook(config)
  File "/home/XXXX/Downloads/bulk-downloader-for-reddit-2/.eggs/pbr-5.5.1-py3.8.egg/pbr/hooks/__init__.py", line 25, in setup_hook
    metadata_config.run()
  File "/home/XXXX/Downloads/bulk-downloader-for-reddit-2/.eggs/pbr-5.5.1-py3.8.egg/pbr/hooks/base.py", line 27, in run
    self.hook()
  File "/home/XXXX/Downloads/bulk-downloader-for-reddit-2/.eggs/pbr-5.5.1-py3.8.egg/pbr/hooks/metadata.py", line 25, in hook
    self.config['version'] = packaging.get_version(
  File "/home/XXXX/Downloads/bulk-downloader-for-reddit-2/.eggs/pbr-5.5.1-py3.8.egg/pbr/packaging.py", line 874, in get_version
    raise Exception("Versioning for this project requires either an sdist"
Exception: Versioning for this project requires either an sdist tarball, or access to an upstream git repository. It's also possible that there is a mismatch between the package name in setup.cfg and the argument given to pbr.version.VersionInfo. Project name Bulk Downloader for Reddit was given, but was not able to be found.
error in setup command: Error parsing /home/farooq/Downloads/bulk-downloader-for-reddit-2/setup.cfg: Exception: Versioning for this project requires either an sdist tarball, or access to an upstream git repository. It's also possible that there is a mismatch between the package name in setup.cfg and the argument given to pbr.version.VersionInfo. Project name Bulk Downloader for Reddit was given, but was not able to be found.
```

**Comment by Serene-Arc** [comment]
What happens if you try and install through `python3 -m pip install .` in the root folder?

**Comment by koeningyou** [comment]
Hi,

I get the following error, with root and non-root permissions;

```
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-gci4i4o9/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-gci4i4o9/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-req-build-gci4i4o9/pip-egg-info
         cwd: /tmp/pip-req-build-gci4i4o9/
    Complete output (16 lines):
    ERROR:root:Error parsing
    Traceback (most recent call last):
      File "/tmp/pip-req-build-gci4i4o9/.eggs/pbr-5.5.1-py3.8.egg/pbr/core.py", line 96, in pbr
        attrs = util.cfg_to_args(path, dist.script_args)
      File "/tmp/pip-req-build-gci4i4o9/.eggs/pbr-5.5.1-py3.8.egg/pbr/util.py", line 271, in cfg_to_args
        pbr.hooks.setup_hook(config)
      File "/tmp/pip-req-build-gci4i4o9/.eggs/pbr-5.5.1-py3.8.egg/pbr/hooks/__init__.py", line 25, in setup_hook
        metadata_config.run()
      File "/tmp/pip-req-build-gci4i4o9/.eggs/pbr-5.5.1-py3.8.egg/pbr/hooks/base.py", line 27, in run
        self.hook()
      File "/tmp/pip-req-build-gci4i4o9/.eggs/pbr-5.5.1-py3.8.egg/pbr/hooks/metadata.py", line 25, in hook
        self.config['version'] = packaging.get_version(
      File "/tmp/pip-req-build-gci4i4o9/.eggs/pbr-5.5.1-py3.8.egg/pbr/packaging.py", line 874, in get_version
        raise Exception("Versioning for this project requires either an sdist"
    Exception: Versioning for this project requires either an sdist tarball, or access to an upstream git repository. It's also possible that there is a mismatch between the package name in setup.cfg and the argument given to pbr.version.VersionInfo. Project name Bulk Downloader for Reddit was given, but was not able to be found.
    error in setup command: Error parsing /tmp/pip-req-build-gci4i4o9/setup.cfg: Exception: Versioning for this project requires either an sdist tarball, or access to an upstream git repository. It's also possible that there is a mismatch between the package name in setup.cfg and the argument given to pbr.version.VersionInfo. Project name Bulk Downloader for Reddit was given, but was not able to be found.
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by Serene-Arc** [comment]
Have you cloned this github repository or downloaded it in some other way?

**Comment by koeningyou** [comment]
Hi,

I downloaded the v2 zip file in this repo and extracted it to a directory.

**Comment by Serene-Arc** [comment]
That is the issue, can you clone the repository through git? The setup manager, pbr, is searching for a way to version the repository. It is designed to be used in a git repository or with a sdist tarball. We haven't made the tarball yet since it's under active development.

If you can't or don't want to clone the repository, you can try setting the pbr version forcefully with the following command:

```bash
export PBR_VERSION=0.1.0
```
