### ISSUE TITLE
Error when post title has unicode escape character

### ISSUE THREAD

**Issue by aliparlakci** [aliparlakci/bulk-downloader-for-reddit#223]
Fails to download a post with title "My cat\u2019s paws are so cute"

https://www.reddit.com/user/aliparlakci/comments/mecwk7/my_catu2019s_paws_are_so_cute/

```bash
❯ python3.9 -m bulkredditdownloader download /mnt/c/Users/aliparlakci/Desktop/saved --link "https://reddit.com/mecwk7" --verbose
[2021-03-27 15:32:57,028 - bulkredditdownloader.downloader - DEBUG] - Loading configuration from /home/aliparlakci/.config/bulkredditdownloader/default_config.cfg
[2021-03-27 15:32:57,028 - bulkredditdownloader.downloader - DEBUG] - Configuration loaded from /home/aliparlakci/.config/bulkredditdownloader/default_config.cfg
[2021-03-27 15:32:57,029 - bulkredditdownloader.downloader - DEBUG] - Using unauthenticated Reddit instance
[2021-03-27 15:32:57,030 - bulkredditdownloader.downloader - DEBUG] - Attempting to download submission mecwk7
[2021-03-27 15:32:58,516 - bulkredditdownloader.downloader - DEBUG] - Using Direct with url https://i.pinimg.com/236x/7d/06/bb/7d06bbbe3cdec081ad54163643f233b3.jpg
[2021-03-27 15:32:58,520 - root - ERROR] - Downloader exited unexpectedly
Traceback (most recent call last):
  File "/usr/lib/python3.9/sre_parse.py", line 1039, in parse_template
    this = chr(ESCAPES[this][1])
KeyError: '\\u'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/aliparlakci/source/bulk-downloader-for-reddit/bulkredditdownloader/__main__.py", line 61, in cli_download
    reddit_downloader.download()
  File "/home/aliparlakci/source/bulk-downloader-for-reddit/bulkredditdownloader/downloader.py", line 327, in download
    self._download_submission(submission)
  File "/home/aliparlakci/source/bulk-downloader-for-reddit/bulkredditdownloader/downloader.py", line 349, in _download_submission
    for destination, res in self.file_name_formatter.format_resource_paths(content, self.download_directory):
  File "/home/aliparlakci/source/bulk-downloader-for-reddit/bulkredditdownloader/file_name_formatter.py", line 82, in format_resource_paths
    out.append((self.format_path(resources[0], destination_directory, None), resources[0]))
  File "/home/aliparlakci/source/bulk-downloader-for-reddit/bulkredditdownloader/file_name_formatter.py", line 58, in format_path
    file_name = str(self._format_name(resource.source_submission, self.file_format_string))
  File "/home/aliparlakci/source/bulk-downloader-for-reddit/bulkredditdownloader/file_name_formatter.py", line 42, in _format_name
    result = re.sub(r'(?i){{{}}}'.format(key), attribute, result)
  File "/usr/lib/python3.9/re.py", line 210, in sub
    return _compile(pattern, flags).sub(repl, string, count)
  File "/usr/lib/python3.9/re.py", line 327, in _subx
    template = _compile_repl(template, pattern)
  File "/usr/lib/python3.9/re.py", line 318, in _compile_repl
    return sre_parse.parse_template(repl, pattern)
  File "/usr/lib/python3.9/sre_parse.py", line 1042, in parse_template
    raise s.error('bad escape %s' % this, len(this))
re.error: bad escape \u at position 6
Traceback (most recent call last):
  File "/usr/lib/python3.9/sre_parse.py", line 1039, in parse_template
    this = chr(ESCAPES[this][1])
KeyError: '\\u'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/aliparlakci/source/bulk-downloader-for-reddit/bulkredditdownloader/__main__.py", line 105, in <module>
    cli()
  File "/home/aliparlakci/.local/lib/python3.9/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/aliparlakci/.local/lib/python3.9/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/aliparlakci/.local/lib/python3.9/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/aliparlakci/.local/lib/python3.9/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/aliparlakci/.local/lib/python3.9/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/aliparlakci/.local/lib/python3.9/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/aliparlakci/source/bulk-downloader-for-reddit/bulkredditdownloader/__main__.py", line 61, in cli_download
    reddit_downloader.download()
  File "/home/aliparlakci/source/bulk-downloader-for-reddit/bulkredditdownloader/downloader.py", line 327, in download
    self._download_submission(submission)
  File "/home/aliparlakci/source/bulk-downloader-for-reddit/bulkredditdownloader/downloader.py", line 349, in _download_submission
    for destination, res in self.file_name_formatter.format_resource_paths(content, self.download_directory):
  File "/home/aliparlakci/source/bulk-downloader-for-reddit/bulkredditdownloader/file_name_formatter.py", line 82, in format_resource_paths
    out.append((self.format_path(resources[0], destination_directory, None), resources[0]))
  File "/home/aliparlakci/source/bulk-downloader-for-reddit/bulkredditdownloader/file_name_formatter.py", line 58, in format_path
    file_name = str(self._format_name(resource.source_submission, self.file_format_string))
  File "/home/aliparlakci/source/bulk-downloader-for-reddit/bulkredditdownloader/file_name_formatter.py", line 42, in _format_name
    result = re.sub(r'(?i){{{}}}'.format(key), attribute, result)
  File "/usr/lib/python3.9/re.py", line 210, in sub
    return _compile(pattern, flags).sub(repl, string, count)
  File "/usr/lib/python3.9/re.py", line 327, in _subx
    template = _compile_repl(template, pattern)
  File "/usr/lib/python3.9/re.py", line 318, in _compile_repl
    return sre_parse.parse_template(repl, pattern)
  File "/usr/lib/python3.9/sre_parse.py", line 1042, in parse_template
    raise s.error('bad escape %s' % this, len(this))
re.error: bad escape \u at position 6
```

**Comment by Serene-Arc** [comment]
Are you using the latest code? This might have been fixed with #222 and if not, I'll have to investigate further

**Comment by Serene-Arc** [comment]
@aliparlakci is this still an issue or should it be closed as fixed?

**Comment by aliparlakci** [comment]
This is still an issue.
