### ISSUE TITLE
Unable to get V2 working

### ISSUE THREAD

**Issue by b2311e** [aliparlakci/bulk-downloader-for-reddit#259]
I'm no doubt doing something wrong, but I can't get V2 working

```
python3 -m bulkredditdownloader
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/brad/bdfr2/bulkredditdownloader/__main__.py", line 8, in <module>
    from bulkredditdownloader.archiver import Archiver
  File "/home/brad/bdfr2/bulkredditdownloader/archiver.py", line 14, in <module>
    from bulkredditdownloader.archive_entry.submission_archive_entry import SubmissionArchiveEntry
  File "/home/brad/bdfr2/bulkredditdownloader/archive_entry/submission_archive_entry.py", line 13, in <module>
    class SubmissionArchiveEntry(BaseArchiveEntry):
  File "/home/brad/bdfr2/bulkredditdownloader/archive_entry/submission_archive_entry.py", line 41, in SubmissionArchiveEntry
    def _get_comments(self) -> list[dict]:
TypeError: 'type' object is not subscriptable
```

**Comment by aliparlakci** [comment]
You are using Python3.8. Can you try with Python3.9?

**Comment by b2311e** [comment]
Ahhh that was it, thank you!
