### ISSUE TITLE
Downloads error if URI fragment present

### ISSUE THREAD

**Issue by Boo1098** [aliparlakci/bulk-downloader-for-reddit#266]
On posts where the a user incorrectly adds a fragment to the URI of a direct file, the download fails.

Example:
```
python3 -m bdfr download -l mpsrds /tmp -v
[2021-04-12 22:44:36,195 - bdfr.downloader - DEBUG] - Loading configuration from /home/froppy/.config/bdfr/default_config.cfg
[2021-04-12 22:44:36,195 - bdfr.downloader - DEBUG] - Setting maximum download wait time to 120 seconds
[2021-04-12 22:44:36,196 - bdfr.downloader - DEBUG] - Using unauthenticated Reddit instance
[2021-04-12 22:44:36,196 - bdfr.downloader - DEBUG] - Attempting to download submission mpsrds
[2021-04-12 22:44:36,508 - bdfr.downloader - DEBUG] - Using Direct with url https://i.redd.it/gtz9yxa4lus61.jpg#test
Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/froppy/src/bulk-downloader-for-reddit/bdfr/__main__.py", line 117, in <module>
    cli()
  File "/home/froppy/.local/lib/python3.9/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/froppy/.local/lib/python3.9/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/froppy/.local/lib/python3.9/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/froppy/.local/lib/python3.9/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/froppy/.local/lib/python3.9/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/froppy/.local/lib/python3.9/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/froppy/src/bulk-downloader-for-reddit/bdfr/__main__.py", line 64, in cli_download
    reddit_downloader.download()
  File "/home/froppy/src/bulk-downloader-for-reddit/bdfr/downloader.py", line 361, in download
    self._download_submission(submission)
  File "/home/froppy/src/bulk-downloader-for-reddit/bdfr/downloader.py", line 383, in _download_submission
    for destination, res in self.file_name_formatter.format_resource_paths(content, self.download_directory):
  File "/home/froppy/src/bulk-downloader-for-reddit/bdfr/file_name_formatter.py", line 135, in format_resource_paths
    out.append((self.format_path(resources[0], destination_directory, None), resources[0]))
  File "/home/froppy/src/bulk-downloader-for-reddit/bdfr/file_name_formatter.py", line 105, in format_path
    raise BulkDownloaderException(f'Resource from {resource.url} has no extension')
bdfr.exceptions.BulkDownloaderException: Resource from https://i.redd.it/gtz9yxa4lus61.jpg#test has no extension
```
This also blocks further downloads from happening if downloaded from a subreddit for example since bdfr exits.

**Comment by Serene-Arc** [comment]
PR #264 closes this
