### ISSUE TITLE
v2-beta: Posts with '\' character in title failing to download

### ISSUE THREAD

**Issue by kc2rxo** [aliparlakci/bulk-downloader-for-reddit#267]
Example output with `--verbose` on using v2:

```
Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/adam/bulk-downloader-for-reddit/bdfr/__main__.py", line 117, in <module>
    cli()
  File "/home/adam/.local/lib/python3.9/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/adam/.local/lib/python3.9/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/adam/.local/lib/python3.9/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/adam/.local/lib/python3.9/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/adam/.local/lib/python3.9/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/adam/.local/lib/python3.9/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/adam/bulk-downloader-for-reddit/bdfr/__main__.py", line 64, in cli_download
    reddit_downloader.download()
  File "/home/adam/bulk-downloader-for-reddit/bdfr/downloader.py", line 361, in download
    self._download_submission(submission)
  File "/home/adam/bulk-downloader-for-reddit/bdfr/downloader.py", line 383, in _download_submission
    for destination, res in self.file_name_formatter.format_resource_paths(content, self.download_directory):
  File "/home/adam/bulk-downloader-for-reddit/bdfr/file_name_formatter.py", line 136, in format_resource_paths
    out.append((self.format_path(resources[0], destination_directory, None), resources[0]))
  File "/home/adam/bulk-downloader-for-reddit/bdfr/file_name_formatter.py", line 107, in format_path
    file_name = str(self._format_name(resource.source_submission, self.file_format_string))
  File "/home/adam/bulk-downloader-for-reddit/bdfr/file_name_formatter.py", line 48, in _format_name
    result = re.sub(fr'(?i){{{key}}}', key_value, result,)
  File "/usr/lib/python3.9/re.py", line 210, in sub
    return _compile(pattern, flags).sub(repl, string, count)
  File "/usr/lib/python3.9/re.py", line 327, in _subx
    template = _compile_repl(template, pattern)
  File "/usr/lib/python3.9/re.py", line 318, in _compile_repl
    return sre_parse.parse_template(repl, pattern)
  File "/usr/lib/python3.9/sre_parse.py", line 1036, in parse_template
    addgroup(int(this[1:]), len(this) - 1)
  File "/usr/lib/python3.9/sre_parse.py", line 980, in addgroup
    raise s.error("invalid group reference %d" % index, pos)
re.error: invalid group reference 4 at position 30
```

Is this a simple add to the `_convert_unicode_escape` or is there something more here I am missing?

**Comment by Serene-Arc** [comment]
This information really doesn't tell me anything about how to recreate this. Can you please provide the detailed log file, or at least the submission ID that caused this error?

**Comment by kc2rxo** [comment]
Sure. Submission ID was `mp8a7j`. I won't post a link here as it is NSFW.

To recreate; I saved the post on reddit and attempted to download using 
`python3 -m bdfr download --user me --saved --authenticate`

**Comment by Serene-Arc** [comment]
It's actually somewhat impressive this hasn't caused an issue up till now, thanks for pointing it out.
