### ISSUE TITLE
v2 - failing with TypeError

### ISSUE THREAD

**Issue by c2lknt** [aliparlakci/bulk-downloader-for-reddit#275]
I started getting this error today - worked just fine a couple of days ago.

I use this line in my script: 

`python3 -m bdfr download --user [username] --upvoted --authenticate -L $1 --file-scheme '{REDDITOR}_{SUBREDDIT}_{TITLE}' ./output/`

And as of today it fails with the following:

```
Traceback (most recent call last):
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/Users/[username]/bulk-downloader-for-reddit/bdfr/__main__.py", line 8, in <module>
    from bdfr.archiver import Archiver
  File "/Users/[username]/bulk-downloader-for-reddit/bdfr/archiver.py", line 15, in <module>
    from bdfr.archive_entry.submission_archive_entry import SubmissionArchiveEntry
  File "/Users/[username]/bulk-downloader-for-reddit/bdfr/archive_entry/submission_archive_entry.py", line 13, in <module>
    class SubmissionArchiveEntry(BaseArchiveEntry):
  File "/Users/[username]/bulk-downloader-for-reddit/bdfr/archive_entry/submission_archive_entry.py", line 41, in SubmissionArchiveEntry
    def _get_comments(self) -> list[dict]:
TypeError: 'type' object is not subscriptable
```

I updated via git pull, same error.  Thoughts?

**Comment by aliparlakci** [comment]
BDfR requires Python3.9 at minimum
