### ISSUE TITLE
First try and got 403 error forbidden xD

### ISSUE THREAD

**Issue by scriptzteam** [aliparlakci/bulk-downloader-for-reddit#3]
```
urllib.error.HTTPError: HTTP Error 403: Forbidden

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "script.py", line 402, in <module>
    main()
  File "script.py", line 396, in main
    downloader(getPosts())
  File "script.py", line 348, in downloader
    updateBackup(BACKUP_FILE,str(i+1),"add")
  File "script.py", line 204, in updateBackup
    getattr(FILE,mode) (key)
  File "/root/bulk-downloader-for-reddit/src/tools.py", line 44, in add
    data = {**data, **toBeAdded}
TypeError: 'str' object is not a mapping

```

**Comment by aliparlakci** [comment]
That bug is fixed. Try the latest commit on master branch.
