### ISSUE TITLE
[BUG] errors when trying to download submission with exceptionally long name

### ISSUE THREAD

**Issue by ekcire06** [aliparlakci/bulk-downloader-for-reddit#300]
- [x] I am reporting a bug.
- [x] I am running the latest version of BDfR
- [x] I have read the [Opening an issue](README.md#configuration)
  
## Description
seems to error when trying to download submission with too long a name

## Command
```
python -m bdfr download --subreddit LiminalSpace -L 150000 --no-dupes --sort top --time all --exclude-id hljj99 D:\projectliminal
```

## Environment (please complete the following information):
 - OS: [e.g. Windows 10]
 - Python version: [e.g. 3.9.4]

## Logs
```
Traceback (most recent call last):
  File "C:\Users\Cole II\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Cole II\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\Cole II\AppData\Local\Programs\Python\Python39\lib\site-packages\bdfr\__main__.py", line 118, in <module>
    cli()
  File "C:\Users\Cole II\AppData\Local\Programs\Python\Python39\lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\Cole II\AppData\Local\Programs\Python\Python39\lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "C:\Users\Cole II\AppData\Local\Programs\Python\Python39\lib\site-packages\click\core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\Cole II\AppData\Local\Programs\Python\Python39\lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\Cole II\AppData\Local\Programs\Python\Python39\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "C:\Users\Cole II\AppData\Local\Programs\Python\Python39\lib\site-packages\click\decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "C:\Users\Cole II\AppData\Local\Programs\Python\Python39\lib\site-packages\bdfr\__main__.py", line 65, in cli_download
    reddit_downloader.download()
  File "C:\Users\Cole II\AppData\Local\Programs\Python\Python39\lib\site-packages\bdfr\downloader.py", line 372, in download
    self._download_submission(submission)
  File "C:\Users\Cole II\AppData\Local\Programs\Python\Python39\lib\site-packages\bdfr\downloader.py", line 416, in _download_submission
    with open(destination, 'wb') as file:
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\projectliminal\\LiminalSpace\\certainclock_i grew up mormon. the churches always had that liminal feeling of existing outside the laws of time and nature, in a way that left a pit in my stomach. something about them is cold, bleak. now i have a strong attachment to limina_j6cd02_1.jpg'
```

**Comment by ekcire06** [comment]
typo moment

**Comment by ekcire06** [comment]
nevermind v1 problem
