### ISSUE TITLE
[BUG] Attempting to download a suspended users' submitted posts causes the downloader to crash

### ISSUE THREAD

**Issue by tayyyTF** [aliparlakci/bulk-downloader-for-reddit#301]
- [x] I am reporting a bug.
- [x] I am running the latest version of BDfR
- [x] I have read the [Opening an issue](README.md#configuration)
  
## Description

Attempting to download the submitted posts from a Reddit user that was suspended causes a crash. Accounts that don't exist or were deleted are correctly identified with "User _username_ does not exist", but if the account was suspended it seems to mess things up.

## Command

python3.9 -m bdfr download --user "Bree-Boo" --submitted test/

## Environment (please complete the following information):
 - OS: Linux (Windows Subsystem for Linux - Ubuntu)
 - Python version: 3.9.0+

## Logs
[2021-04-23 05:28:37,411 - bdfr.downloader - DEBUG] - Setting maximum download wait time to 120 seconds
[2021-04-23 05:28:37,412 - bdfr.downloader - Level 9] - Created download filter
[2021-04-23 05:28:37,412 - bdfr.downloader - Level 9] - Created time filter
[2021-04-23 05:28:37,412 - bdfr.downloader - Level 9] - Created sort filter
[2021-04-23 05:28:37,412 - bdfr.downloader - Level 9] - Create file name formatter
[2021-04-23 05:28:37,412 - bdfr.downloader - DEBUG] - Using unauthenticated Reddit instance
[2021-04-23 05:28:37,421 - bdfr.downloader - Level 9] - Created site authenticator
[2021-04-23 05:28:37,421 - bdfr.downloader - Level 9] - Retrieved subreddits
[2021-04-23 05:28:37,421 - bdfr.downloader - Level 9] - Retrieved multireddits
[2021-04-23 05:28:37,689 - root - ERROR] - Downloader exited unexpectedly
Traceback (most recent call last):
  File "/home/username/.local/lib/python3.9/site-packages/bdfr/__main__.py", line 64, in cli_download
    reddit_downloader = RedditDownloader(config)
  File "/home/username/.local/lib/python3.9/site-packages/bdfr/downloader.py", line 67, in __init__
    self.reddit_lists = self._retrieve_reddit_lists()
  File "/home/username/.local/lib/python3.9/site-packages/bdfr/downloader.py", line 152, in _retrieve_reddit_lists
    master_list.extend(self._get_user_data())
  File "/home/username/.local/lib/python3.9/site-packages/bdfr/downloader.py", line 307, in _get_user_data
    if not self._check_user_existence(self.args.user):
  File "/home/username/.local/lib/python3.9/site-packages/bdfr/downloader.py", line 335, in _check_user_existence
    if not user.id:
  File "/usr/local/lib/python3.9/dist-packages/praw/models/reddit/base.py", line 35, in __getattr__
    return getattr(self, attribute)
  File "/usr/local/lib/python3.9/dist-packages/praw/models/reddit/base.py", line 36, in __getattr__
    raise AttributeError(
AttributeError: 'Redditor' object has no attribute 'id'

**Comment by Serene-Arc** [comment]
Yeah, there is only minimal difference on the backend between a deleted account and a non-existent account. Actually it's only the fact that the name and the `is_suspended` variables remain the same. Otherwise it will behave the same way in all of the checks that we have to ensure that a user is real. I'll see if I can narrow down a way to let deleted/suspended accounts through.

**Comment by Serene-Arc** [comment]
It appears that Reddit does not allow this at all. Maybe we can find whether an account is suspended or not, but we can't access any of their data; attempting to do so results in a HTTP 403 error, which means that I'm attempting to access forbidden data. Unfortunately there is no way for us to bypass this. 

It might be possible for there to be a specific error message when accessing a banned account, so I'll leave this issue open until I write that.

**Comment by Serene-Arc** [comment]
A separate issue would be good for that thanks. Private subreddits would work if you are authenticated and a member of it already. But we should definitely handle those errors so please open one.

**Comment by tayyyTF** [comment]
Thanks! Sounds good, I'll make a separate issue.
