### ISSUE TITLE
[BUG] Gfycat/GifDeliveryNetwork/RedGIFs AttributeError and RedGIFs "could not read the page source".

### ISSUE THREAD

**Issue by StuffonGithub** [aliparlakci/bulk-downloader-for-reddit#316]
- [x] I am reporting a bug.
- [x] I am running the latest version of BDfR *(running latest development branch)*
- [x] I have read the [Opening an issue](README.md#configuration)
  
## Description
So, I'm starting with the NSFW part of the archive and immediately noticed a couple errors affecting all the subreddits and users I've tried so far (given that the ones I've tried all contained RedGIFs links or converted Gfycat links).

The AttributeError causes BDFR to exit thereby not downloading the rest of the posts. Whereas, the RedGIFs page source error only skips the current submission and continues on to the next one.

Manually visiting the links that cause each of the errors shows that the GIFs are still available/viewable.

Not sure if both issues are connected or not. So. I'm only doing a single post in the meantime. Do let me know if they should be separated and I will do so.

## Command
```
python3 -m bdfr download 'directory\Subreddit' --subreddit SUBREDDIT --sort new --no-dupes --folder-scheme '{SUBREDDIT}' --file-scheme '{DATE}_{SUBREDDIT}_{TITLE}_{POSTID}' --log 'directory/SUBREDDIT.txt'
```

## Environment (please complete the following information):
 - OS: Windows 10 20H2
 - Python version: 3.9.4

## Logs
```
[2021-04-28 19:30:24,081 - root - ERROR] - Downloader exited unexpectedly
Traceback (most recent call last):
  File "directory\bulk-downloader-for-reddit\bdfr\__main__.py", line 66, in cli_download
    reddit_downloader.download()
  File "directory\bulk-downloader-for-reddit\bdfr\downloader.py", line 386, in download
    self._download_submission(submission)
  File "directory\bulk-downloader-for-reddit\bdfr\downloader.py", line 404, in _download_submission
    content = downloader.find_resources(self.authenticator)
  File "directory\bulk-downloader-for-reddit\bdfr\site_downloaders\gfycat.py", line 21, in find_resources
    return super().find_resources(authenticator)
  File "directory\bulk-downloader-for-reddit\bdfr\site_downloaders\gif_delivery_network.py", line 20, in find_resources
    media_url = self._get_link(self.post.url)
  File "directory\bulk-downloader-for-reddit\bdfr\site_downloaders\gfycat.py", line 36, in _get_link
    out = json.loads(content.contents[0])['video']['contentUrl']
AttributeError: 'NoneType' object has no attribute 'contents'
```
and
```
[2021-04-28 19:27:57,563 - bdfr.downloader - DEBUG] - Attempting to download submission {POSTID}
[2021-04-28 19:27:57,563 - bdfr.downloader - DEBUG] - Using Redgifs with url https://redgifs.com/watch/randomsomethinganimal
[2021-04-28 19:27:58,648 - bdfr.downloader - ERROR] - Site Redgifs failed to download submission {POSTID}: Could not read the page source
```

**Comment by Serene-Arc** [comment]
If you pull the latest changes from branch `development`, it'll work. Redgifs and the associated Gif Delivery Network changed their site so that our scraping algorithm no longer worked. It was fixed last night :)

**Comment by StuffonGithub** [comment]
Ah thank you. I could have sworn I checked if there were recent commits before opening the issue but probably just got a brainfart. Lol.

**Comment by Serene-Arc** [comment]
That error was because you changed the file without a commit, or committed something yourself. In the future, you can use `git reset --hard .` to reset the folder to the state that git knows. You'll lose any changes though with that, but the `git pull` should work afterwards.

**Comment by StuffonGithub** [comment]
Huh, weird since I haven't made an edit to any of the files in the BDFR git folder. But thanks for the reset command though! I searched for a list of basic Git commands when I was "troubleshooting" it earlier and I somehow didn't see that one. I'm missing too many things today. Lol.

Nevertheless, thank you so much for the patience and the stuff you're teaching me. 😊
