### ISSUE TITLE
[BUG] Filenames exceed the MAX_PATH limit of Windows

### ISSUE THREAD

**Issue by aliparlakci** [aliparlakci/bulk-downloader-for-reddit#385]
## Description
Filenames exceeds the MAX_PATH limit of Windows

## Command
```
python -m bdfr archive ~/Desktop/hello --all-comments --user me
```

## Environment (please complete the following information):
 - OS: Windows 10
 - Python version: 3.9.4

## Logs
```
[2021-05-16 15:24:27,202 - bdfr.downloader - DEBUG] - Setting maximum download wait time to 120 seconds
[2021-05-16 15:24:27,202 - bdfr.downloader - DEBUG] - Setting datetime format string to ISO
[2021-05-16 15:24:27,203 - bdfr.downloader - Level 9] - Created download filter
[2021-05-16 15:24:27,203 - bdfr.downloader - Level 9] - Created time filter
[2021-05-16 15:24:27,203 - bdfr.downloader - Level 9] - Created sort filter
[2021-05-16 15:24:27,203 - bdfr.downloader - Level 9] - Create file name formatter
[2021-05-16 15:24:27,203 - bdfr.downloader - DEBUG] - Using authenticated Reddit instance
[2021-05-16 15:24:27,203 - bdfr.downloader - Level 9] - Commencing OAuth2 authentication
[2021-05-16 15:24:27,607 - bdfr.oauth2 - WARNING] - Authentication action required before the program can proceed
[2021-05-16 15:24:27,608 - bdfr.oauth2 - WARNING] - Authenticate at https://www.reddit.com/api/v1/authorize?client_id=U-6gk4ZCh3IeNQ&duration=permanent&redirect_uri=http%3A%2F%2Flocalhost%3A7634&response_type=code&scope=identity+read+history+save&state=47870
[2021-05-16 15:24:27,610 - bdfr.oauth2 - Level 9] - Server listening on 0.0.0.0:7634
[2021-05-16 15:24:41,642 - bdfr.oauth2 - Level 9] - Server closed
[2021-05-16 15:24:42,046 - bdfr.oauth2 - Level 9] - Loaded OAuth2 token for authoriser
[2021-05-16 15:24:42,493 - bdfr.oauth2 - Level 9] - Written OAuth2 token from authoriser to C:\Users\aliparlakci\AppData\Local\BDFR\bdfr\default_config.cfg
[2021-05-16 15:24:42,946 - bdfr.downloader - Level 9] - Resolved user to aliparlakci
[2021-05-16 15:24:42,946 - bdfr.downloader - Level 9] - Created site authenticator
[2021-05-16 15:24:42,946 - bdfr.downloader - Level 9] - Retrieved subreddits
[2021-05-16 15:24:42,946 - bdfr.downloader - Level 9] - Retrieved multireddits
[2021-05-16 15:24:42,946 - bdfr.archiver - DEBUG] - Retrieving comments of user aliparlakci
[2021-05-16 15:24:42,947 - bdfr.downloader - Level 9] - Retrieved user data
[2021-05-16 15:24:42,947 - bdfr.downloader - Level 9] - Retrieved submissions for given links
[2021-05-16 15:24:43,991 - bdfr.archiver - DEBUG] - Attempting to archive submission gyba24d
[2021-05-16 15:24:45,314 - bdfr.archiver - DEBUG] - Writing entry gyba24d to file in JSON format at C:\Users\aliparlakci\Desktop\hello\DataHoarder\aliparlakci_Bulk Downloader for Reddit, tool for archiving reddit, has a major release!_gyba24d.json
[2021-05-16 15:24:45,314 - bdfr.archiver - INFO] - Record for entry item gyba24d written to disk
[2021-05-16 15:26:21,087 - bdfr.archiver - DEBUG] - Attempting to archive submission er558z3
[2021-05-16 15:26:25,017 - root - ERROR] - Downloader exited unexpectedly
Traceback (most recent call last):
  File "C:\Users\aliparlakci\source\bulk-downloader-for-reddit\bdfr\__main__.py", line 86, in cli_archive
    reddit_archiver.download()
  File "C:\Users\aliparlakci\source\bulk-downloader-for-reddit\bdfr\archiver.py", line 32, in download
    self._write_entry(submission)
  File "C:\Users\aliparlakci\source\bulk-downloader-for-reddit\bdfr\archiver.py", line 65, in _write_entry
    self._write_entry_json(archive_entry)
  File "C:\Users\aliparlakci\source\bulk-downloader-for-reddit\bdfr\archiver.py", line 77, in _write_entry_json
    self._write_content_to_disk(resource, content)
  File "C:\Users\aliparlakci\source\bulk-downloader-for-reddit\bdfr\archiver.py", line 92, in _write_content_to_disk
    with open(file_path, 'w', encoding="utf-8") as file:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\aliparlakci\\Desktop\\hello\\Showerthoughts\\aliparlakci_If you are cautious enough to carry one of those pointy car window-breakers in case you drive your car into a lake, you are probably cautious enough to not drive your car into a lake in the first place._er558z3.json'
```

**Comment by Serene-Arc** [comment]
Huh. This is supposed to be addressed in the code, I guess it doesn't actually trigger correctly on Windows.

**Comment by aliparlakci** [comment]
This issue is starting to annoy me. I am now considering removing the entire title of the post from filename if it is too long, instead of trying to make it shorter. Then, suggest people disabling MAX_PATH in their systems if they continue to have post titles in filenames.

**Comment by Serene-Arc** [comment]
No, I think that the issues should be handled similarly. It's a quirk of Windows, on Linux the maxc path length is 4096 characters and on Windows it's 260. I'll write a fix

**Comment by st-korn** [comment]
See https://www.howtogeek.com/266621/how-to-make-windows-10-accept-file-paths-over-260-characters/
how to fix this problem on Windows 10
