### ISSUE TITLE
[BUG] Program exits on 'Connection reset by peer' error

### ISSUE THREAD

**Issue by dbanon87** [aliparlakci/bulk-downloader-for-reddit#402]
- [x] I am reporting a bug.
- [x] I am running the latest version of BDfR
- [x] I have read the [Opening an issue](../../README.md#configuration)
  
## Description

This chain of exceptions occurred while downloading a user's posts. It appears that maybe this type of exception is not caught and treated as transient.

Using BDFR 2.1.1 installed via `python3 -m pip install bdfr --upgrade`.

```
Traceback (most recent call last):
 File "/home/me/downloader/env3.9/lib/python3.9/site-packages/urllib3/response.py", line 438, in _error_catcher
   yield
 File "/home/me/downloader/env3.9/lib/python3.9/site-packages/urllib3/response.py", line 519, in read
   data = self._fp.read(amt) if not fp_closed else b""
 File "/usr/local/lib/python3.9/http/client.py", line 455, in read
   n = self.readinto(b)
 File "/usr/local/lib/python3.9/http/client.py", line 499, in readinto
   n = self.fp.readinto(b)
 File "/usr/local/lib/python3.9/socket.py", line 704, in readinto
   return self._sock.recv_into(b)
 File "/usr/local/lib/python3.9/ssl.py", line 1241, in recv_into
   return self.read(nbytes, buffer)
 File "/usr/local/lib/python3.9/ssl.py", line 1099, in read
   return self._sslobj.read(len, buffer)
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "/home/me/downloader/env3.9/lib/python3.9/site-packages/requests/models.py", line 753, in generate
   for chunk in self.raw.stream(chunk_size, decode_content=True):
 File "/home/me/downloader/env3.9/lib/python3.9/site-packages/urllib3/response.py", line 576, in stream
   data = self.read(amt=amt, decode_content=decode_content)
 File "/home/me/downloader/env3.9/lib/python3.9/site-packages/urllib3/response.py", line 541, in read
   raise IncompleteRead(self._fp_bytes_read, self.length_remaining)
 File "/usr/local/lib/python3.9/contextlib.py", line 135, in __exit__
   self.gen.throw(type, value, traceback)
 File "/home/me/downloader/env3.9/lib/python3.9/site-packages/urllib3/response.py", line 455, in _error_catcher
   raise ProtocolError("Connection broken: %!r(MISSING)" %!e(MISSING), e)
urllib3.exceptions.ProtocolError: ("Connection broken: ConnectionResetError(104, 'Connection reset by peer')", ConnectionResetError(104, 'Connection reset by peer'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "/usr/local/lib/python3.9/runpy.py", line 197, in _run_module_as_main
   return _run_code(code, main_globals, None,
 File "/usr/local/lib/python3.9/runpy.py", line 87, in _run_code
   exec(code, run_globals)
 File "/home/me/downloader/env3.9/lib/python3.9/site-packages/bdfr/__main__.py", line 120, in <module>
   cli()
 File "/home/me/downloader/env3.9/lib/python3.9/site-packages/click/core.py", line 1134, in __call__
   return self.main(*args, **kwargs)
 File "/home/me/downloader/env3.9/lib/python3.9/site-packages/click/core.py", line 1059, in main
   rv = self.invoke(ctx)
 File "/home/me/downloader/env3.9/lib/python3.9/site-packages/click/core.py", line 1665, in invoke
   return _process_result(sub_ctx.command.invoke(sub_ctx))
 File "/home/me/downloader/env3.9/lib/python3.9/site-packages/click/core.py", line 1401, in invoke
   return ctx.invoke(self.callback, **ctx.params)
 File "/home/me/downloader/env3.9/lib/python3.9/site-packages/click/core.py", line 767, in invoke
   return __callback(*args, **kwargs)
 File "/home/me/downloader/env3.9/lib/python3.9/site-packages/click/decorators.py", line 26, in new_func
   return f(get_current_context(), *args, **kwargs)
 File "/home/me/downloader/env3.9/lib/python3.9/site-packages/bdfr/__main__.py", line 67, in cli_download
   reddit_downloader.download()
 File "/home/me/downloader/env3.9/lib/python3.9/site-packages/bdfr/downloader.py", line 397, in download
   self._download_submission(submission)
 File "/home/me/downloader/env3.9/lib/python3.9/site-packages/bdfr/downloader.py", line 423, in _download_submission
   res.download(self.args.max_wait_time)
 File "/home/me/downloader/env3.9/lib/python3.9/site-packages/bdfr/resource.py", line 54, in download
   content = self.retry_download(self.url, max_wait_time)
 File "/home/me/downloader/env3.9/lib/python3.9/site-packages/bdfr/resource.py", line 34, in retry_download
   response = requests.get(url)
 File "/home/me/downloader/env3.9/lib/python3.9/site-packages/requests/api.py", line 76, in get
   return request('get', url, params=params, **kwargs)
 File "/home/me/downloader/env3.9/lib/python3.9/site-packages/requests/api.py", line 61, in request
   return session.request(method=method, url=url, **kwargs)
 File "/home/me/downloader/env3.9/lib/python3.9/site-packages/requests/sessions.py", line 542, in request
   resp = self.send(prep, **send_kwargs)
 File "/home/me/downloader/env3.9/lib/python3.9/site-packages/requests/sessions.py", line 697, in send
   r.content
 File "/home/me/downloader/env3.9/lib/python3.9/site-packages/requests/models.py", line 831, in content
   self._content = b''.join(self.iter_content(CONTENT_CHUNK_SIZE)) or b''
 File "/home/me/downloader/env3.9/lib/python3.9/site-packages/requests/models.py", line 756, in generate
   raise ChunkedEncodingError(e)
requests.exceptions.ChunkedEncodingError: ("Connection broken: ConnectionResetError(104, 'Connection reset by peer')", ConnectionResetError(104, 'Connection reset by peer'))
```

## Command

```
./env3.9/bin/python3 -m bdfr download \
        "/downloads/u_$USER" \
        --submitted --time week --user "$USER" \
        --sort top
```

## Environment
 - OS: Debian 10
 - Python version: 3.9.5

## Logs

Unfortunately I cannot find the logfile for this run.

**Comment by aliparlakci** [comment]
We will fix it as soon as possible. But "Unfortunately I cannot find the logfile for this run." concerned me. Have you installed Python from Windows Store?

**Comment by dbanon87** [comment]
> But "Unfortunately I cannot find the logfile for this run." concerned me. Have you installed Python from Windows Store?

No, I am running this on Debian and installed Python to `/usr/local` from source.

All "Unfortunately I cannot find the logfile for this run" means is that I mixed up the naming pattern used for `--log` in the script that calls BDFR, so I don't know which log file on my disk correlates with this run.

**Comment by aliparlakci** [comment]
Sorry, I didn't check your OS and assumed that you are on Windows. We had a "missing log files" bug on Windows systems and I was afraid that it occurred again.

**Comment by dbanon87** [comment]
> Sorry, I didn't check your OS and assumed that you are on Windows. We had a "missing log files" bug on Windows systems and I was afraid that it occurred again.

Ah, I understand. Nope, that isn't the case here, just my failing to put sufficient detail in log file names.
