### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by matt00112233** [aliparlakci/bulk-downloader-for-reddit#455]
- [x] I am reporting a bug.
- [x] I am running the latest version of BDfR
- [x] I have read the [Opening an issue](https://github.com/aliparlakci/bulk-downloader-for-reddit/blob/master/docs/CONTRIBUTING.md#opening-an-issue)
  
## Description
Downloading upvoted Reddit posts abruptly stops 

## Command
```
python -m bdfr download ./path/to/output --user matt00112233 --upvoted --limit 266 --authenticate
```

## Environment (please complete the following information):
 - OS: [e.g. Windows 10]
 - Python version: [e.g. 3.9.4]

## Logs
```
[2021-06-09 22:01:04,530 - bdfr.downloader - ERROR] - Failed to write file to C:\Users\Yoga 14\path\to\output\ThotNetwork\KatieCarmine_I POST A NEW VIDEO ALMOST EVERYDAY AND YOU NEVER HAVE TO PAY EXTRA FOR IT! I want to share my sex life with you! Only $6 per month and you get full access to over 400 videos of me getting fuck_nnboza.mp4 in submission nnboza: [Errno 2] No such file or directory: 'C:\\Users\\Yoga 14\\path\\to\\output\\ThotNetwork\\KatieCarmine_I POST A NEW VIDEO ALMOST EVERYDAY AND YOU NEVER HAVE TO PAY EXTRA FOR IT! I want to share my sex life with you! Only $6 per month and you get full access to over 400 videos of me getting fuck_nnboza.mp4'
Traceback (most recent call last):
  File "C:\Users\Yoga 14\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Yoga 14\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\Yoga 14\AppData\Local\Programs\Python\Python39\lib\site-packages\bdfr\__main__.py", line 151, in <module>
    cli()
  File "C:\Users\Yoga 14\AppData\Local\Programs\Python\Python39\lib\site-packages\click\core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\Yoga 14\AppData\Local\Programs\Python\Python39\lib\site-packages\click\core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "C:\Users\Yoga 14\AppData\Local\Programs\Python\Python39\lib\site-packages\click\core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\Yoga 14\AppData\Local\Programs\Python\Python39\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\Yoga 14\AppData\Local\Programs\Python\Python39\lib\site-packages\click\core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\Yoga 14\AppData\Local\Programs\Python\Python39\lib\site-packages\click\decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "C:\Users\Yoga 14\AppData\Local\Programs\Python\Python39\lib\site-packages\bdfr\__main__.py", line 80, in cli_download
    reddit_downloader.download()
  File "C:\Users\Yoga 14\AppData\Local\Programs\Python\Python39\lib\site-packages\bdfr\downloader.py", line 45, in download
    self._download_submission(submission)
  File "C:\Users\Yoga 14\AppData\Local\Programs\Python\Python39\lib\site-packages\bdfr\downloader.py", line 108, in _download_submission
    os.utime(destination, (creation_time, creation_time))
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'C:\\Users\\Yoga 14\\path\\to\\output\\ThotNetwork\\KatieCarmine_I POST A NEW VIDEO ALMOST EVERYDAY AND YOU NEVER HAVE TO PAY EXTRA FOR IT! I want to share my sex life with you! Only $6 per month and you get full access to over 400 videos of me getting fuck_nnboza.mp4'
```

**Comment by Serene-Arc** [comment]
Are you actually using the latest version of the BDFR, v2.2.0?

**Comment by matt00112233** [comment]
Yes, I am currently using the latest version 2.2.0. I had to exclude the conflictual posts/submissions in order to be able to continue downloading other posts/submissions

**Comment by Serene-Arc** [comment]
Please provide the unedited section of the logfile in question so I can see what's actually happening.

**Comment by matt00112233** [comment]
Here it is and thank you again:


C:\Users\Yoga 14>python -m bdfr download ./path/to/output --user matt00112233 --upvoted --limit 278 --authenticate
[2021-06-09 22:32:22,039 - bdfr.downloader - INFO] - Downloaded submission nvt3s5 from ThotX
[2021-06-09 22:32:22,158 - bdfr.downloader - INFO] - Downloaded submission nvvsp8 from ThotX
[2021-06-09 22:32:22,262 - bdfr.downloader - INFO] - Downloaded submission nvw5h1 from ThotX
[2021-06-09 22:32:22,360 - bdfr.downloader - INFO] - Downloaded submission nvv47o from ThotX
[2021-06-09 22:32:22,463 - bdfr.downloader - INFO] - Downloaded submission nw7ori from ThotX
[2021-06-09 22:32:22,593 - bdfr.downloader - INFO] - Downloaded submission nw6w3n from ThotX
[2021-06-09 22:32:22,700 - bdfr.downloader - INFO] - Downloaded submission nwa46v from ThotX
[2021-06-09 22:32:22,719 - bdfr.downloader - INFO] - Downloaded submission nwa2fj from ThotX
[2021-06-09 22:32:22,814 - bdfr.downloader - INFO] - Downloaded submission nwaln1 from ThotX
[2021-06-09 22:32:22,917 - bdfr.downloader - INFO] - Downloaded submission nhdjd5 from ThotNetwork
[2021-06-09 22:32:23,045 - bdfr.downloader - INFO] - Downloaded submission nhoqxy from ThotNetwork
[2021-06-09 22:32:23,158 - bdfr.downloader - INFO] - Downloaded submission nhc4pb from ThotNetwork
[2021-06-09 22:32:23,384 - bdfr.downloader - INFO] - Downloaded submission nhonhq from ThotNetwork
[2021-06-09 22:32:23,487 - bdfr.downloader - INFO] - Downloaded submission ni3bkn from ThotNetwork
[2021-06-09 22:32:23,621 - bdfr.downloader - ERROR] - Site Redgifs failed to download submission niz9ud: Server responded with 404 to https://api.redgifs.com/v1/gfycats/sorethisdouglasfirbarkbeetle
[2021-06-09 22:32:23,714 - bdfr.downloader - INFO] - Downloaded submission nir0fm from ThotNetwork
[2021-06-09 22:32:23,824 - bdfr.downloader - INFO] - Downloaded submission nj3ahj from ThotNetwork
[2021-06-09 22:32:23,939 - bdfr.downloader - INFO] - Downloaded submission nj1jde from ThotNetwork
[2021-06-09 22:32:24,082 - bdfr.downloader - INFO] - Downloaded submission nj978r from ThotNetwork
[2021-06-09 22:32:24,193 - bdfr.downloader - INFO] - Downloaded submission njskjt from ThotNetwork
[2021-06-09 22:32:24,305 - bdfr.downloader - INFO] - Downloaded submission njswgq from ThotNetwork
[2021-06-09 22:32:24,426 - bdfr.downloader - INFO] - Downloaded submission njwhmo from ThotNetwork
[2021-06-09 22:32:24,564 - bdfr.downloader - INFO] - Downloaded submission njzfxh from ThotNetwork
[2021-06-09 22:32:24,677 - bdfr.downloader - INFO] - Downloaded submission nkeehi from ThotNetwork
[2021-06-09 22:32:24,793 - bdfr.downloader - INFO] - Downloaded submission nl295g from ThotNetwork
[2021-06-09 22:32:24,902 - bdfr.downloader - INFO] - Downloaded submission nmslh6 from ThotNetwork
[2021-06-09 22:32:25,055 - bdfr.downloader - INFO] - Downloaded submission nlk5p3 from ThotNetwork
[2021-06-09 22:32:25,156 - bdfr.downloader - INFO] - Downloaded submission nnaz3h from ThotNetwork
[2021-06-09 22:32:25,249 - bdfr.downloader - INFO] - Downloaded submission nnhstt from ThotNetwork
[2021-06-09 22:32:25,358 - bdfr.downloader - INFO] - Downloaded submission no6vhh from ThotNetwork
[2021-06-09 22:32:26,047 - bdfr.downloader - ERROR] - Failed to download resource https://thumbs2.redgifs.com/UsefulCautiousRodent.mp4 in submission no53xn with downloader Redgifs: Unrecoverable error requesting resource: HTTP Code 404
[2021-06-09 22:32:26,139 - bdfr.downloader - INFO] - Downloaded submission no4nny from ThotNetwork
[2021-06-09 22:32:26,227 - bdfr.downloader - INFO] - Downloaded submission nocjzc from ThotNetwork
[2021-06-09 22:32:26,356 - bdfr.downloader - INFO] - Downloaded submission nofj1t from ThotNetwork
[2021-06-09 22:32:26,521 - bdfr.downloader - INFO] - Downloaded submission noy655 from ThotNetwork
[2021-06-09 22:32:26,615 - bdfr.downloader - INFO] - Downloaded submission np0428 from ThotNetwork
[2021-06-09 22:32:26,704 - bdfr.downloader - INFO] - Downloaded submission nq4pzc from ThotNetwork
[2021-06-09 22:32:26,794 - bdfr.downloader - INFO] - Downloaded submission nph9rt from ThotNetwork
[2021-06-09 22:32:26,900 - bdfr.downloader - INFO] - Downloaded submission npk9yt from ThotNetwork
[2021-06-09 22:32:27,027 - bdfr.downloader - INFO] - Downloaded submission nqzhiu from ThotNetwork
[2021-06-09 22:32:27,130 - bdfr.downloader - INFO] - Downloaded submission ns211a from ThotNetwork
[2021-06-09 22:32:27,237 - bdfr.downloader - INFO] - Downloaded submission ns5plp from ThotNetwork
[2021-06-09 22:32:27,341 - bdfr.downloader - INFO] - Downloaded submission nsepq9 from ThotNetwork
[2021-06-09 22:32:27,479 - bdfr.downloader - INFO] - Downloaded submission nihc0g from ThotNetwork
[2021-06-09 22:32:27,604 - bdfr.downloader - INFO] - Downloaded submission nhgv31 from ThotNetwork
[2021-06-09 22:32:27,715 - bdfr.downloader - INFO] - Downloaded submission nj0mfo from ThotNetwork
[2021-06-09 22:32:27,845 - bdfr.downloader - INFO] - Downloaded submission niizrr from ThotNetwork
[2021-06-09 22:32:27,966 - bdfr.downloader - INFO] - Downloaded submission njz43y from ThotNetwork
[2021-06-09 22:32:28,108 - bdfr.downloader - INFO] - Downloaded submission njfw3d from ThotNetwork
[2021-06-09 22:32:28,260 - bdfr.downloader - INFO] - Downloaded submission nm306d from ThotNetwork
[2021-06-09 22:32:28,362 - bdfr.downloader - INFO] - Downloaded submission nmr3st from ThotNetwork
[2021-06-09 22:32:28,469 - bdfr.downloader - INFO] - Downloaded submission nmu3nu from ThotNetwork
[2021-06-09 22:32:28,634 - bdfr.downloader - INFO] - Downloaded submission npfosk from ThotNetwork
[2021-06-09 22:32:28,738 - bdfr.downloader - INFO] - Downloaded submission npnbyn from ThotNetwork
[2021-06-09 22:32:28,843 - bdfr.downloader - INFO] - Downloaded submission nqkk7r from ThotNetwork
[2021-06-09 22:32:28,952 - bdfr.downloader - INFO] - Downloaded submission nrgzwq from ThotNetwork
[2021-06-09 22:32:29,092 - bdfr.downloader - INFO] - Downloaded submission nd248n from ThotNetwork
[2021-06-09 22:32:29,227 - bdfr.downloader - INFO] - Downloaded submission nhq11j from ThotNetwork
[2021-06-09 22:32:29,401 - bdfr.downloader - INFO] - Downloaded submission nig4zi from ThotNetwork
[2021-06-09 22:32:29,557 - bdfr.downloader - INFO] - Downloaded submission ninp6p from ThotNetwork
[2021-06-09 22:32:29,780 - bdfr.downloader - INFO] - Downloaded submission nj9urs from ThotNetwork
[2021-06-09 22:32:29,931 - bdfr.downloader - INFO] - Downloaded submission njwobn from ThotNetwork
[2021-06-09 22:32:30,067 - bdfr.downloader - INFO] - Downloaded submission njdogd from ThotNetwork
[2021-06-09 22:32:30,231 - bdfr.downloader - INFO] - Downloaded submission nlpmh2 from ThotNetwork
[2021-06-09 22:32:30,451 - bdfr.downloader - INFO] - Downloaded submission nlxry6 from ThotNetwork
[2021-06-09 22:32:30,680 - bdfr.downloader - INFO] - Downloaded submission no1lbg from ThotNetwork
[2021-06-09 22:32:30,881 - bdfr.downloader - INFO] - Downloaded submission npl3oi from ThotNetwork
[2021-06-09 22:32:31,019 - bdfr.downloader - INFO] - Downloaded submission nq6vrt from ThotNetwork
[2021-06-09 22:32:31,155 - bdfr.downloader - INFO] - Downloaded submission nqyecf from ThotNetwork
[2021-06-09 22:32:31,279 - bdfr.downloader - INFO] - Downloaded submission nhuukw from ThotNetwork
[2021-06-09 22:32:31,297 - bdfr.downloader - INFO] - Downloaded submission nj8uho from ThotNetwork
[2021-06-09 22:32:31,462 - bdfr.downloader - INFO] - Downloaded submission nl94fs from ThotNetwork
[2021-06-09 22:32:35,905 - bdfr.downloader - ERROR] - Failed to write file to C:\Users\Yoga 14\path\to\output\ThotNetwork\Nataliermann1_18 YEARS  JOI  VERY INTERACTIVE  Honest Dick Rates VIDEOS  Daily NUDE Post  Dildo PLAY Anal and Vaginal  Cumming  Customes (Schoolgirl is my favorite)  Dirty stories and videos of all kinds  _nmdyk7.mp4 in submission nmdyk7: [Errno 2] No such file or directory: 'C:\\Users\\Yoga 14\\path\\to\\output\\ThotNetwork\\Nataliermann1_18 YEARS  JOI  VERY INTERACTIVE  Honest Dick Rates VIDEOS  Daily NUDE Post  Dildo PLAY Anal and Vaginal  Cumming  Customes (Schoolgirl is my favorite)  Dirty stories and videos of all kinds  _nmdyk7.mp4'
Traceback (most recent call last):
  File "C:\Users\Yoga 14\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Yoga 14\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\Yoga 14\AppData\Local\Programs\Python\Python39\lib\site-packages\bdfr\__main__.py", line 151, in <module>
    cli()
  File "C:\Users\Yoga 14\AppData\Local\Programs\Python\Python39\lib\site-packages\click\core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\Yoga 14\AppData\Local\Programs\Python\Python39\lib\site-packages\click\core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "C:\Users\Yoga 14\AppData\Local\Programs\Python\Python39\lib\site-packages\click\core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\Yoga 14\AppData\Local\Programs\Python\Python39\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\Yoga 14\AppData\Local\Programs\Python\Python39\lib\site-packages\click\core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\Yoga 14\AppData\Local\Programs\Python\Python39\lib\site-packages\click\decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "C:\Users\Yoga 14\AppData\Local\Programs\Python\Python39\lib\site-packages\bdfr\__main__.py", line 80, in cli_download
    reddit_downloader.download()
  File "C:\Users\Yoga 14\AppData\Local\Programs\Python\Python39\lib\site-packages\bdfr\downloader.py", line 45, in download
    self._download_submission(submission)
  File "C:\Users\Yoga 14\AppData\Local\Programs\Python\Python39\lib\site-packages\bdfr\downloader.py", line 108, in _download_submission
    os.utime(destination, (creation_time, creation_time))
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'C:\\Users\\Yoga 14\\path\\to\\output\\ThotNetwork\\Nataliermann1_18 YEARS  JOI  VERY INTERACTIVE  Honest Dick Rates VIDEOS  Daily NUDE Post  Dildo PLAY Anal and Vaginal  Cumming  Customes (Schoolgirl is my favorite)  Dirty stories and videos of all kinds  _nmdyk7.mp4'

C:\Users\Yoga 14>FileNotFoundError: [WinError 3] The system cannot find the path specified:
'FileNotFoundError:' is not recognized as an internal or external command,
operable program or batch file.
