### ISSUE TITLE
[BUG] configparser.NoOptionError: No option 'scopes' in section: 'DEFAULT'

### ISSUE THREAD

**Issue by dbanon87** [aliparlakci/bulk-downloader-for-reddit#460]
- [x] I am reporting a bug.
- [x] I am running the latest version of BDfR
- [x] I have read the [Opening an issue](https://github.com/aliparlakci/bulk-downloader-for-reddit/blob/master/docs/CONTRIBUTING.md#opening-an-issue)
  
## Description

When trying to download my saved posts, the program crashes with the error `configparser.NoOptionError: No option 'scopes' in section: 'DEFAULT'`.

## Command

```
./env3.9/bin/python3 -m bdfr download \
	"/path/to/archive" \
	--log "/home/me/log/bdfr/saved_$(date +%Y%m%d_%H%M%S).log" \
	--make-hard-links \
	--saved \
	--user me --authenticate
```

## Environment (please complete the following information):
 - OS: Debian 10
 - Python version: Python 3.9.5

## Logs
```
Traceback (most recent call last):
 File "/usr/local/lib/python3.9/configparser.py", line 789, in get
   value = d[option]
 File "/home/me/downloader/env3.9/lib/python3.9/collections/__init__.py", line 941, in __getitem__
   return self.__missing__(key)            # support subclasses that define __missing__
 File "/home/me/downloader/env3.9/lib/python3.9/collections/__init__.py", line 933, in __missing__
   raise KeyError(key)
KeyError: 'scopes'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "/usr/local/lib/python3.9/runpy.py", line 197, in _run_module_as_main
   return _run_code(code, main_globals, None,
 File "/usr/local/lib/python3.9/runpy.py", line 87, in _run_code
   exec(code, run_globals)
 File "/home/me/downloader/env3.9/lib/python3.9/site-packages/bdfr/__main__.py", line 151, in <module>
   cli()
 File "/home/me/downloader/env3.9/lib/python3.9/site-packages/click/core.py", line 1134, in __call__
   return self.main(*args, **kwargs)
 File "/home/me/downloader/env3.9/lib/python3.9/site-packages/click/core.py", line 1059, in main
   rv = self.invoke(ctx)
 File "/home/me/downloader/env3.9/lib/python3.9/site-packages/click/core.py", line 1665, in invoke
   return _process_result(sub_ctx.command.invoke(sub_ctx))
 File "/home/me/downloader/env3.9/lib/python3.9/site-packages/click/core.py", line 1401, in invoke
   return ctx.invoke(self.callback, **ctx.params)
 File "/home/me/downloader/env3.9/lib/python3.9/site-packages/click/core.py", line 767, in invoke
   return __callback(*args, **kwargs)
 File "/home/me/downloader/env3.9/lib/python3.9/site-packages/click/decorators.py", line 26, in new_func
   return f(get_current_context(), *args, **kwargs)
 File "/home/me/downloader/env3.9/lib/python3.9/site-packages/bdfr/__main__.py", line 79, in cli_download
   reddit_downloader = RedditDownloader(config)
 File "/home/me/downloader/env3.9/lib/python3.9/site-packages/bdfr/downloader.py", line 38, in __init__
   super(RedditDownloader, self).__init__(args)
 File "/home/me/downloader/env3.9/lib/python3.9/site-packages/bdfr/connector.py", line 56, in __init__
   self._setup_internal_objects()
 File "/home/me/downloader/env3.9/lib/python3.9/site-packages/bdfr/connector.py", line 78, in _setup_internal_objects
   self.create_reddit_instance()
 File "/home/me/downloader/env3.9/lib/python3.9/site-packages/bdfr/connector.py", line 122, in create_reddit_instance
   scopes = self.cfg_parser.get('DEFAULT', 'scopes')
 File "/usr/local/lib/python3.9/configparser.py", line 792, in get
   raise NoOptionError(option, section)
configparser.NoOptionError: No option 'scopes' in section: 'DEFAULT'
```

**Comment by Serene-Arc** [comment]
This is from the configuration file missing a line. It should be handled better and I'll write up a fix, but in the meantime you can fix this by coping the scopes line from the example/default configuration file.
