### ISSUE TITLE
[BUG] Can no longer download saved posts

### ISSUE THREAD

**Issue by SonnySN** [aliparlakci/bulk-downloader-for-reddit#463]
- [x] I am reporting a bug.
- [x] I am running the latest version of BDfR
- [x] I have read the [Opening an issue](https://github.com/aliparlakci/bulk-downloader-for-reddit/blob/master/docs/CONTRIBUTING.md#opening-an-issue)
  
## Description
I am trying to download saved posts, previously had no issue, but my drive started to fail. So when I switched the drive out, for a new one, I can no longer download saved posts. Regular submission posts download normally. 
[log_output.txt](https://github.com/aliparlakci/bulk-downloader-for-reddit/files/6681645/log_output.txt)

## Command
python -m bdfr download B:\BDFR --user me --saved --authenticate --file-scheme '{TITLE}''{POSTID}'

```

## Environment (please complete the following information):
 - OS: Windows 10
 - Python version: 3.9

## Logs

[2021-06-19 22:19:21,110 - bdfr.connector - DEBUG] - Setting maximum download wait time to 120 seconds
[2021-06-19 22:19:21,110 - bdfr.connector - DEBUG] - Setting datetime format string to ISO
[2021-06-19 22:19:21,111 - bdfr.connector - DEBUG] - Disabling the following modules: 
[2021-06-19 22:19:21,111 - bdfr.connector - Level 9] - Created download filter
[2021-06-19 22:19:21,111 - bdfr.connector - Level 9] - Created time filter
[2021-06-19 22:19:21,111 - bdfr.connector - Level 9] - Created sort filter
[2021-06-19 22:19:21,111 - bdfr.connector - Level 9] - Create file name formatter
[2021-06-19 22:19:21,111 - bdfr.connector - DEBUG] - Using authenticated Reddit instance
[2021-06-19 22:19:21,113 - bdfr.oauth2 - Level 9] - Loaded OAuth2 token for authoriser
[2021-06-19 22:19:21,355 - root - ERROR] - Downloader exited unexpectedly
Traceback (most recent call last):
  File "C:\Users\sonny\AppData\Local\Programs\Python\Python39\lib\site-packages\bdfr\__main__.py", line 79, in cli_download
    reddit_downloader = RedditDownloader(config)
  File "C:\Users\sonny\AppData\Local\Programs\Python\Python39\lib\site-packages\bdfr\downloader.py", line 38, in __init__
    super(RedditDownloader, self).__init__(args)
  File "C:\Users\sonny\AppData\Local\Programs\Python\Python39\lib\site-packages\bdfr\connector.py", line 56, in __init__
    self._setup_internal_objects()
  File "C:\Users\sonny\AppData\Local\Programs\Python\Python39\lib\site-packages\bdfr\connector.py", line 79, in _setup_internal_objects
    self.args.user = list(filter(None, [self.resolve_user_name(user) for user in self.args.user]))
  File "C:\Users\sonny\AppData\Local\Programs\Python\Python39\lib\site-packages\bdfr\connector.py", line 79, in <listcomp>
    self.args.user = list(filter(None, [self.resolve_user_name(user) for user in self.args.user]))
  File "C:\Users\sonny\AppData\Local\Programs\Python\Python39\lib\site-packages\bdfr\connector.py", line 273, in resolve_user_name
    resolved_name = self.reddit_instance.user.me().name
  File "C:\Users\sonny\AppData\Local\Programs\Python\Python39\lib\site-packages\praw\models\user.py", line 155, in me
    user_data = self._reddit.get(API_PATH["me"])
  File "C:\Users\sonny\AppData\Local\Programs\Python\Python39\lib\site-packages\praw\reddit.py", line 566, in get
    return self._objectify_request(method="GET", params=params, path=path)
  File "C:\Users\sonny\AppData\Local\Programs\Python\Python39\lib\site-packages\praw\reddit.py", line 667, in _objectify_request
    self.request(
  File "C:\Users\sonny\AppData\Local\Programs\Python\Python39\lib\site-packages\praw\reddit.py", line 849, in request
    return self._core.request(
  File "C:\Users\sonny\AppData\Local\Programs\Python\Python39\lib\site-packages\prawcore\sessions.py", line 328, in request
    return self._request_with_retries(
  File "C:\Users\sonny\AppData\Local\Programs\Python\Python39\lib\site-packages\prawcore\sessions.py", line 226, in _request_with_retries
    response, saved_exception = self._make_request(
  File "C:\Users\sonny\AppData\Local\Programs\Python\Python39\lib\site-packages\prawcore\sessions.py", line 183, in _make_request
    response = self._rate_limiter.call(
  File "C:\Users\sonny\AppData\Local\Programs\Python\Python39\lib\site-packages\prawcore\rate_limit.py", line 33, in call
    kwargs["headers"] = set_header_callback()
  File "C:\Users\sonny\AppData\Local\Programs\Python\Python39\lib\site-packages\prawcore\sessions.py", line 281, in _set_header_callback
    self._authorizer.refresh()
  File "C:\Users\sonny\AppData\Local\Programs\Python\Python39\lib\site-packages\prawcore\auth.py", line 254, in refresh
    self._request_token(
  File "C:\Users\sonny\AppData\Local\Programs\Python\Python39\lib\site-packages\prawcore\auth.py", line 155, in _request_token
    response = self._authenticator._post(url, **data)
  File "C:\Users\sonny\AppData\Local\Programs\Python\Python39\lib\site-packages\prawcore\auth.py", line 38, in _post
    raise ResponseException(response)
prawcore.exceptions.ResponseException: received 400 HTTP response

**Comment by Serene-Arc** [comment]
Try updating praw with `python3 -m pip install -U praw`, that error doesn't come from anything to do with the BDFR specifically. praw received an update recently and it's possible the backend changed

**Comment by SonnySN** [comment]
Hi thanks for the reply, I forgot to mention I updated praw before to see if it would change things, and it does not seem to change the issue at the time. I tried updating again just now. Also Attached is the new but i think same log after the attempted praw update. 
[log_output.txt](https://github.com/aliparlakci/bulk-downloader-for-reddit/files/6682627/log_output.txt)


##
C:\Users\sonny>python -m pip install -U praw
Requirement already satisfied: praw in c:\users\sonny\appdata\local\programs\python\python39\lib\site-packages (7.3.0)
Requirement already satisfied: update-checker>=0.18 in c:\users\sonny\appdata\local\programs\python\python39\lib\site-packages (from praw) (0.18.0)
Requirement already satisfied: websocket-client>=0.54.0 in c:\users\sonny\appdata\local\programs\python\python39\lib\site-packages (from praw) (0.58.0)
Requirement already satisfied: prawcore<3,>=2.1 in c:\users\sonny\appdata\local\programs\python\python39\lib\site-packages (from praw) (2.2.0)
Requirement already satisfied: requests<3.0,>=2.6.0 in c:\users\sonny\appdata\local\programs\python\python39\lib\site-packages (from prawcore<3,>=2.1->praw) (2.25.1)
Requirement already satisfied: chardet<5,>=3.0.2 in c:\users\sonny\appdata\local\programs\python\python39\lib\site-packages (from requests<3.0,>=2.6.0->prawcore<3,>=2.1->praw) (4.0.0)
Requirement already satisfied: idna<3,>=2.5 in c:\users\sonny\appdata\local\programs\python\python39\lib\site-packages (from requests<3.0,>=2.6.0->prawcore<3,>=2.1->praw) (2.10)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\sonny\appdata\local\programs\python\python39\lib\site-packages (from requests<3.0,>=2.6.0->prawcore<3,>=2.1->praw) (2020.12.5)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\users\sonny\appdata\local\programs\python\python39\lib\site-packages (from requests<3.0,>=2.6.0->prawcore<3,>=2.1->praw) (1.26.4)
Requirement already satisfied: six in c:\users\sonny\appdata\local\programs\python\python39\lib\site-packages (from websocket-client>=0.54.0->praw) (1.15.0)

**Comment by aliparlakci** [comment]
It is most probably because your token is empty in the `default_config.cfg` file. This file lives next to `log_output.txt` You can just delete it and start the program. However, if it doesn't ask you to login with `--authenticated` option although you deleted the `default_config.cfg`, then there is another `default_config.cfg` file. Be sure to delete all the config files that contain your login information, or at least corrupted login information :)

**Comment by SonnySN** [comment]
Thank you that fixed the issue. The files are downloading no problem again! :D

**Comment by slabvizgig** [comment]
- [x] I am running the latest version of BDfR

- [x] I have read the [Opening an issue](https://github.com/aliparlakci/bulk-downloader-for-reddit/blob/master/docs/CONTRIBUTING.md#opening-an-issue)

## Description

Hi, I thought I would open up this thread again because I'm having a very similar issue on mac. I've researched extensively and tried to delete both `default_config.cfg` files to no avail. They seem to have been stored in `opt/homebrow/config` and `/opt/homebrew/lib/python3.10/site-packages/bdfr/` respectively. I can't seem to locate `log_output.txt` for the life of me. I thought this would be the best course of action before heading straight to bug reporting.
[log_file.txt](https://github.com/aliparlakci/bulk-downloader-for-reddit/files/9577822/log_file.txt).


## Environment:
 - OS: macOS 12.6
 - python version: 3.10

## Command
`python3 -m bdfr download ./path/to/output --user me --saved --authenticate`

## Logs

Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.10/
3.10.6_2/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/homebrew/Cellar/python@3.10/3.10.6_2/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/opt/homebrew/lib/python3.10/site-packages/bdfr/__main__.py", line 154, in <module>
    cli()
  File "/opt/homebrew/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/opt/homebrew/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/opt/homebrew/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/homebrew/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/homebrew/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/opt/homebrew/lib/python3.10/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/opt/homebrew/lib/python3.10/site-packages/bdfr/__main__.py", line 82, in cli_download
    reddit_downloader = RedditDownloader(config)
  File "/opt/homebrew/lib/python3.10/site-packages/bdfr/downloader.py", line 38, in __init__
    super(RedditDownloader, self).__init__(args)
  File "/opt/homebrew/lib/python3.10/site-packages/bdfr/connector.py", line 57, in __init__
    self._setup_internal_objects()
  File "/opt/homebrew/lib/python3.10/site-packages/bdfr/connector.py", line 80, in _setup_internal_objects
    self.args.user = list(filter(None, [self.resolve_user_name(user) for user in self.args.user]))
  File "/opt/homebrew/lib/python3.10/site-packages/bdfr/connector.py", line 80, in <listcomp>
    self.args.user = list(filter(None, [self.resolve_user_name(user) for user in self.args.user]))
  File "/opt/homebrew/lib/python3.10/site-packages/bdfr/connector.py", line 280, in resolve_user_name
    resolved_name = self.reddit_instance.user.me().name
  File "/opt/homebrew/lib/python3.10/site-packages/praw/util/deprecate_args.py", line 43, in wrapped
    return func(**dict(zip(_old_args, args)), **kwargs)
  File "/opt/homebrew/lib/python3.10/site-packages/praw/models/user.py", line 168, in me
    user_data = self._reddit.get(API_PATH["me"])
  File "/opt/homebrew/lib/python3.10/site-packages/praw/util/deprecate_args.py", line 43, in wrapped
    return func(**dict(zip(_old_args, args)), **kwargs)
  File "/opt/homebrew/lib/python3.10/site-packages/praw/reddit.py", line 634, in get
    return self._objectify_request(method="GET", params=params, path=path)
  File "/opt/homebrew/lib/python3.10/site-packages/praw/reddit.py", line 739, in _objectify_request
    self.request(
  File "/opt/homebrew/lib/python3.10/site-packages/praw/util/deprecate_args.py", line 43, in wrapped
    return func(**dict(zip(_old_args, args)), **kwargs)
  File "/opt/homebrew/lib/python3.10/site-packages/praw/reddit.py", line 941, in request
    return self._core.request(
  File "/opt/homebrew/lib/python3.10/site-packages/prawcore/sessions.py", line 330, in request
    return self._request_with_retries(
  File "/opt/homebrew/lib/python3.10/site-packages/prawcore/sessions.py", line 228, in _request_with_retries
    response, saved_exception = self._make_request(
  File "/opt/homebrew/lib/python3.10/site-packages/prawcore/sessions.py", line 185, in _make_request
    response = self._rate_limiter.call(
  File "/opt/homebrew/lib/python3.10/site-packages/prawcore/rate_limit.py", line 33, in call
    kwargs["headers"] = set_header_callback()
  File "/opt/homebrew/lib/python3.10/site-packages/prawcore/sessions.py", line 283, in _set_header_callback
    self._authorizer.refresh()
  File "/opt/homebrew/lib/python3.10/site-packages/prawcore/auth.py", line 254, in refresh
    self._request_token(
  File "/opt/homebrew/lib/python3.10/site-packages/prawcore/auth.py", line 155, in _request_token
    response = self._authenticator._post(url, **data)
  File "/opt/homebrew/lib/python3.10/site-packages/prawcore/auth.py", line 38, in _post
    raise ResponseException(response)
prawcore.exceptions.ResponseException: received 400 HTTP response

Any help and/or insight on this is greatly appreciated!
