### ISSUE TITLE
[BUG] [Errno 2] No such file or directory: [WinError 3] The system cannot find the path specified:

### ISSUE THREAD

**Issue by adwinair** [aliparlakci/bulk-downloader-for-reddit#474]
- [ x ] I am reporting a bug.
- [ x ] I am running the latest version of bdfr
- [ x ] I have read the [Opening an issue](https://github.com/aliparlakci/bulk-downloader-for-reddit/blob/master/docs/CONTRIBUTING.md#opening-an-issue)
  
## Description
bdfr seems to fail upon hitting certain posts, perhaps a filename length issue.
## Command
```
python -m bdfr download C:\data\BrookeAB_Pics --subreddit BrookeAB_Pics --log C:\data\LOG_FILES\test.log
```

## Environment (please complete the following information):
Windows 10
3.9.5

## Logs
```
[2021-06-26 17:04:42,256 - bdfr.downloader - DEBUG] - Using SelfPost with url https://www.reddit.com/r/BrookeAB_Pics/comments/fxlk12/when_posting_something_on_this_subreddit_make/
[2021-06-26 17:04:52,476 - bdfr.downloader - ERROR] - [Errno 2] No such file or directory: 'C:\\data\\BrookeAB_Pics\\BrookeAB_Pics\\NotMe360_When posting something on this sub-reddit make sure its not weird outside its normality, we are already following a girls pictures thats weird enough, do no post and ask others if they a_fxlk12.txt'
Traceback (most recent call last):
  File "C:\Users\adwinair\AppData\Roaming\Python\Python39\site-packages\bdfr\downloader.py", line 101, in _download_submission
    with open(destination, 'wb') as file:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\data\\BrookeAB_Pics\\BrookeAB_Pics\\NotMe360_When posting something on this sub-reddit make sure its not weird outside its normality, we are already following a girls pictures thats weird enough, do no post and ask others if they a_fxlk12.txt'
[2021-06-26 17:04:52,477 - bdfr.downloader - ERROR] - Failed to write file to C:\data\BrookeAB_Pics\BrookeAB_Pics\NotMe360_When posting something on this sub-reddit make sure its not weird outside its normality, we are already following a girls pictures thats weird enough, do no post and ask others if they a_fxlk12.txt in submission fxlk12: [Errno 2] No such file or directory: 'C:\\data\\BrookeAB_Pics\\BrookeAB_Pics\\NotMe360_When posting something on this sub-reddit make sure its not weird outside its normality, we are already following a girls pictures thats weird enough, do no post and ask others if they a_fxlk12.txt'
[2021-06-26 17:04:52,477 - root - ERROR] - Downloader exited unexpectedly
Traceback (most recent call last):
  File "C:\Users\adwinair\AppData\Roaming\Python\Python39\site-packages\bdfr\__main__.py", line 80, in cli_download
    reddit_downloader.download()
  File "C:\Users\adwinair\AppData\Roaming\Python\Python39\site-packages\bdfr\downloader.py", line 45, in download
    self._download_submission(submission)
  File "C:\Users\adwinair\AppData\Roaming\Python\Python39\site-packages\bdfr\downloader.py", line 108, in _download_submission
    os.utime(destination, (creation_time, creation_time))
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'C:\\data\\BrookeAB_Pics\\BrookeAB_Pics\\NotMe360_When posting something on this sub-reddit make sure its not weird outside its normality, we are already following a girls pictures thats weird enough, do no post and ask others if they a_fxlk12.txt'
```

**Comment by Serene-Arc** [comment]
Are you using the latest development build? This appears to be an issue that's already been fixed.

**Comment by ericzaine** [comment]
I am having the same type of issue and I am using the latest build.

**Comment by Serene-Arc** [comment]
Are you using the development branch?
