### ISSUE TITLE
OSError: [Errno 36] File name too long: 'downloaded/Ooer/DogsRNice_NOo_ØøǾ_ǿÖö_ȪȫÓ_óÒò_ÔôỐ_ốỒồ_ỔổỖ_ỗỘộ_ǑǒŐ_őŎŏ_ȎȏȮ_ȯȰȱ_ỌọƟ_ɵƠơ_ỚớỜ_ờỠỡ_ỢợỞ_ởỎỏ_ŌōṒ_ṓṐṑ_ÕõȬ_ȭṌṍ_ṎṏǪ_ǫȌȍ_O̩o̩Ó̩_ó̩Ò̩ò̩_ǬǭŒ_œ_84r4h5.jpg'

### ISSUE THREAD

**Issue by ra-c** [aliparlakci/bulk-downloader-for-reddit#48]
Just tried saving a random /r/ooer post. Ended up with this error.

**Comment by aliparlakci** [comment]
Can you provide the CONSOLE_LOG.txt file which is located at downloaded/LOG_FILES/ in your condition?

**Comment by Ishidres** [comment]
Same error here. This is the error message logged in the console:
```
(260/985) – r/subredditnameERROR:root:OSError
Traceback (most recent call last):
  File "/home/aliparlakci/.local/lib/python3.6/site-packages/cx_Freeze/initscripts/__startup__.py", line 14, in run
  File "/home/aliparlakci/.local/lib/python3.6/site-packages/cx_Freeze/initscripts/Console.py", line 26, in run
  File "script.py", line 718, in <module>
  File "script.py", line 707, in main
  File "script.py", line 575, in download
  File "script.py", line 482, in isPostExists
  File "/usr/lib/python3.6/pathlib.py", line 1334, in exists
  File "/usr/lib/python3.6/pathlib.py", line 1156, in stat
  File "/usr/lib/python3.6/pathlib.py", line 387, in wrapped
OSError: [Errno 36] File name too long: 'downloads/subredditname/very_long_file_name.jpg'
```
Additional info:
- the filename contained emojis because the post title of the downloaded post contained emojis, too
- the length of the whole filename was 221 characters including the `.jpg` ending

Hope this helps more!

**Comment by 2pid** [comment]
```
(437/998) – r/subredditnameERROR:root:OSError
Traceback (most recent call last):
  File "/home/aliparlakci/.local/lib/python3.6/site-packages/cx_Freeze/initscripts/__startup__.py", line 14, in run
  File "/home/aliparlakci/.local/lib/python3.6/site-packages/cx_Freeze/initscripts/Console.py", line 26, in run
  File "script.py", line 718, in <module>
  File "script.py", line 707, in main
  File "script.py", line 575, in download
  File "script.py", line 482, in isPostExists
  File "/usr/lib/python3.6/pathlib.py", line 1334, in exists
    """
  File "/usr/lib/python3.6/pathlib.py", line 1156, in stat
    os.stat() does.
  File "/usr/lib/python3.6/pathlib.py", line 387, in wrapped
    return strfunc(str(pathobj), *args)
OSError: [Errno 36] File name too long: '231-character-353-byte-long-filename.jpg'
```
---

Hi. Me, too.

Neat app.
