### ISSUE TITLE
[BUG] FileNotFoundError: [Errno 2] Error Persists/[WinError 3] Error Solved

### ISSUE THREAD

**Issue by ericzaine** [aliparlakci/bulk-downloader-for-reddit#488]
- [x] I am reporting a bug.
- [x] I am running the latest version of BDfR
- [x] I have read the [Opening an issue](https://github.com/aliparlakci/bulk-downloader-for-reddit/blob/master/docs/CONTRIBUTING.md#opening-an-issue)
  
## Description

BDFR refuses to download anything after erroring on the first reddit post from the user xJustViolet, saying the file and directory is not found.

## Command
```
python3 -m bdfr download ./downloads --user xjustviolet --submitted --sort new --folder-scheme '{REDDITOR}'

```

## Environment (please complete the following information):
 - OS: Windows 10 Pro 21H1 Build 19043.1083
 - Python version: 3.9.4

## Logs
```
[2021-07-08 17:38:37,686 - bdfr.connector - DEBUG] - Setting maximum download wait time to 120 seconds
[2021-07-08 17:38:37,686 - bdfr.connector - DEBUG] - Setting datetime format string to ISO
[2021-07-08 17:38:37,687 - bdfr.connector - DEBUG] - Disabling the following modules: 
[2021-07-08 17:38:37,687 - bdfr.connector - Level 9] - Created download filter
[2021-07-08 17:38:37,687 - bdfr.connector - Level 9] - Created time filter
[2021-07-08 17:38:37,687 - bdfr.connector - Level 9] - Created sort filter
[2021-07-08 17:38:37,687 - bdfr.connector - Level 9] - Create file name formatter
[2021-07-08 17:38:37,687 - bdfr.connector - DEBUG] - Using unauthenticated Reddit instance
[2021-07-08 17:38:37,688 - bdfr.connector - Level 9] - Created site authenticator
[2021-07-08 17:38:37,688 - bdfr.connector - Level 9] - Retrieved subreddits
[2021-07-08 17:38:37,688 - bdfr.connector - Level 9] - Retrieved multireddits
[2021-07-08 17:38:38,056 - bdfr.connector - DEBUG] - Retrieving submitted posts of user ['xjustviolet']
[2021-07-08 17:38:38,056 - bdfr.connector - Level 9] - Retrieved user data
[2021-07-08 17:38:38,056 - bdfr.connector - Level 9] - Retrieved submissions for given links
[2021-07-08 17:38:39,022 - bdfr.downloader - DEBUG] - Attempting to download submission oby4lp
[2021-07-08 17:38:39,022 - bdfr.downloader - DEBUG] - Using Direct with url https://i.redd.it/2jkaeja5to871.jpg
[2021-07-08 17:38:39,372 - bdfr.downloader - ERROR] - [Errno 2] No such file or directory: 'C:\\Users\\Ericz\\Desktop\\bulk-downloader-for-reddit-master\\bulk-downloader-for-reddit-master\\downloads\\xJustViolet\\xJustViolet_Happy Canada Day!  Wearing red today while fucking my glass dildo, I just uploaded the full video to my onlyfans.comjustviol_oby4lp.jpg'
Traceback (most recent call last):
  File "C:\Users\Ericz\Desktop\bulk-downloader-for-reddit-master\bulk-downloader-for-reddit-master\bdfr\downloader.py", line 101, in _download_submission
    with open(destination, 'wb') as file:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Ericz\\Desktop\\bulk-downloader-for-reddit-master\\bulk-downloader-for-reddit-master\\downloads\\xJustViolet\\xJustViolet_Happy Canada Day!  Wearing red today while fucking my glass dildo, I just uploaded the full video to my onlyfans.comjustviol_oby4lp.jpg'
[2021-07-08 17:38:39,372 - bdfr.downloader - ERROR] - Failed to write file to C:\Users\Ericz\Desktop\bulk-downloader-for-reddit-master\bulk-downloader-for-reddit-master\downloads\xJustViolet\xJustViolet_Happy Canada Day!  Wearing red today while fucking my glass dildo, I just uploaded the full video to my onlyfans.comjustviol_oby4lp.jpg in submission oby4lp: [Errno 2] No such file or directory: 'C:\\Users\\Ericz\\Desktop\\bulk-downloader-for-reddit-master\\bulk-downloader-for-reddit-master\\downloads\\xJustViolet\\xJustViolet_Happy Canada Day!  Wearing red today while fucking my glass dildo, I just uploaded the full video to my onlyfans.comjustviol_oby4lp.jpg'
[2021-07-08 17:38:39,372 - root - ERROR] - Downloader exited unexpectedly
Traceback (most recent call last):
  File "C:\Users\Ericz\Desktop\bulk-downloader-for-reddit-master\bulk-downloader-for-reddit-master\bdfr\__main__.py", line 80, in cli_download
    reddit_downloader.download()
  File "C:\Users\Ericz\Desktop\bulk-downloader-for-reddit-master\bulk-downloader-for-reddit-master\bdfr\downloader.py", line 45, in download
    self._download_submission(submission)
  File "C:\Users\Ericz\Desktop\bulk-downloader-for-reddit-master\bulk-downloader-for-reddit-master\bdfr\downloader.py", line 108, in _download_submission
    os.utime(destination, (creation_time, creation_time))
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'C:\\Users\\Ericz\\Desktop\\bulk-downloader-for-reddit-master\\bulk-downloader-for-reddit-master\\downloads\\xJustViolet\\xJustViolet_Happy Canada Day!  Wearing red today while fucking my glass dildo, I just uploaded the full video to my onlyfans.comjustviol_oby4lp.jpg'

```

**Comment by Serene-Arc** [comment]
Hi. Are you using the latest development build? This issue should have been fixed, there'll be a release with that fix soon.

**Comment by ericzaine** [comment]
Ah thank you, I downloaded the development build and it's working now.

**Comment by ericzaine** [comment]
I am reopening the issue because it is spitting out a lot of errors, some for photos and others mostly for videos.

1:07,456 - bdfr.downloader - DEBUG] - Attempting to download submission n39f7d
[2021-07-09 00:01:07,456 - bdfr.downloader - DEBUG] - Using Direct with url https://i.imgur.com/tGy17aO.jpg
[2021-07-09 00:01:07,605 - bdfr.downloader - ERROR] - [Errno 2] No such file or directory: 'C:\\Users\\Ericz\\Desktop\\bulk-downloader-for-reddit-master\\bulk-downloader-for-reddit-master\\downloads\\xJustViolet\\xJustViolet_I posted this strip down and lotion show on my group premium snapchat The Sinful Seven ) get our snapchat for life for $35 o_n39f7d.jpg'
Traceback (most recent call last):
  File "C:\Users\Ericz\Desktop\bulk-downloader-for-reddit-master\bulk-downloader-for-reddit-master\bdfr\downloader.py", line 104, in _download_submission
    with open(destination, 'wb') as file:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Ericz\\Desktop\\bulk-downloader-for-reddit-master\\bulk-downloader-for-reddit-master\\downloads\\xJustViolet\\xJustViolet_I posted this strip down and lotion show on my group premium snapchat The Sinful Seven ) get our snapchat for life for $35 o_n39f7d.jpg'
[2021-07-09 00:01:07,605 - bdfr.downloader - ERROR] - Failed to write file in submission n39f7d to C:\Users\Ericz\Desktop\bulk-downloader-for-reddit-master\bulk-downloader-for-reddit-master\downloads\xJustViolet\xJustViolet_I posted this strip down and lotion show on my group premium snapchat The Sinful Seven ) get our snapchat for life for $35 o_n39f7d.jpg: [Errno 2] No such file or directory: 'C:\\Users\\Ericz\\Desktop\\bulk-downloader-for-reddit-master\\bulk-downloader-for-reddit-master\\downloads\\xJustViolet\\xJustViolet_I posted this strip down and lotion show on my group premium snapchat The Sinful Seven ) get our snapchat for life for $35 o_n39f7d.jpg'

[2021-07-09 00:01:09,335 - bdfr.downloader - DEBUG] - Attempting to download submission n075um
[2021-07-09 00:01:09,335 - bdfr.downloader - DEBUG] - Using Imgur with url https://i.imgur.com/K1jIkoy.gifv
[2021-07-09 00:01:09,739 - bdfr.downloader - ERROR] - [Errno 2] No such file or directory: 'C:\\Users\\Ericz\\Desktop\\bulk-downloader-for-reddit-master\\bulk-downloader-for-reddit-master\\downloads\\xJustViolet\\xJustViolet_I uploaded Ice elf uses magical butt plug (1124mins) to my onlyfans.comjustviolet ) get instant access to this video & 100s _n075um.mp4'
Traceback (most recent call last):
  File "C:\Users\Ericz\Desktop\bulk-downloader-for-reddit-master\bulk-downloader-for-reddit-master\bdfr\downloader.py", line 104, in _download_submission
    with open(destination, 'wb') as file:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Ericz\\Desktop\\bulk-downloader-for-reddit-master\\bulk-downloader-for-reddit-master\\downloads\\xJustViolet\\xJustViolet_I uploaded Ice elf uses magical butt plug (1124mins) to my onlyfans.comjustviolet ) get instant access to this video & 100s _n075um.mp4'
[2021-07-09 00:01:09,739 - bdfr.downloader - ERROR] - Failed to write file in submission n075um to C:\Users\Ericz\Desktop\bulk-downloader-for-reddit-master\bulk-downloader-for-reddit-master\downloads\xJustViolet\xJustViolet_I uploaded Ice elf uses magical butt plug (1124mins) to my onlyfans.comjustviolet ) get instant access to this video & 100s _n075um.mp4: [Errno 2] No such file or directory: 'C:\\Users\\Ericz\\Desktop\\bulk-downloader-for-reddit-master\\bulk-downloader-for-reddit-master\\downloads\\xJustViolet\\xJustViolet_I uploaded Ice elf uses magical butt plug (1124mins) to my onlyfans.comjustviolet ) get instant access to this video & 100s _n075um.mp4'

**Comment by Serene-Arc** [comment]
Sorry for the long response time but is this still a problem? I've been chasing down various bugs on Windows platforms vis-a-vis errors like this for like the past month or two and there have been a lot of changes to the code that manages this section. One issue is with windows misreporting its max path limit and then erroring out when a file beyond a smaller limit is written.
