### ISSUE TITLE
[BUG] Age Restricted YouTube videos causing crash?

### ISSUE THREAD

**Issue by br54throwaway** [aliparlakci/bulk-downloader-for-reddit#526]
- [x] I am reporting a bug.
- [x] I am running the latest version of BDfR
- [x] I have read the [Opening an issue](https://github.com/aliparlakci/bulk-downloader-for-reddit/blob/master/docs/CONTRIBUTING.md#opening-an-issue)
  
## Description
Upon attempting to download upvoted pictures / videos, the downloader crashed. On reading the log file it appears it crashed on attempting to open an age restricted YouTube video. Un-upvoting said video stopped the error when attempting to re-download, suggesting this was the root cause of the issue.

## Command

python -m bdfr download C:\Users\user\Documents\reddittest1 --upvoted --authenticate --user me

## Environment (please complete the following information):
 - OS: Windows 10
 - Python version: 3.9.7

## Logs
```
Paste the log output here
[2021-09-23 22:00:13,470 - bdfr.downloader - DEBUG] - Attempting to download submission pl13ed
[2021-09-23 22:00:13,471 - bdfr.downloader - DEBUG] - Using Youtube with url https://youtu.be/TMqPOlp4tNo
[2021-09-23 22:00:14,010 - bdfr.site_downloaders.youtube - ERROR] - ERROR: Sign in to confirm your age
This video may be inappropriate for some users.
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\youtube_dl\YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\youtube_dl\YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\youtube_dl\extractor\common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\youtube_dl\extractor\youtube.py", line 1713, in _real_extract
    raise ExtractorError(reason, expected=True)
youtube_dl.utils.ExtractorError: Sign in to confirm your age
This video may be inappropriate for some users.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\bdfr\site_downloaders\youtube.py", line 69, in get_video_attributes
    result = ydl.extract_info(url, download=False)
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\youtube_dl\YoutubeDL.py", line 808, in extract_info
    return self.__extract_info(url, ie, download, extra_info, process)
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\youtube_dl\YoutubeDL.py", line 824, in wrapper
    self.report_error(compat_str(e), e.format_traceback())
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\youtube_dl\YoutubeDL.py", line 628, in report_error
    self.trouble(error_message, tb)
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\youtube_dl\YoutubeDL.py", line 598, in trouble
    raise DownloadError(message, exc_info)
youtube_dl.utils.DownloadError: ERROR: Sign in to confirm your age
This video may be inappropriate for some users.
[2021-09-23 22:00:14,055 - root - ERROR] - Downloader exited unexpectedly
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\bdfr\__main__.py", line 82, in cli_download
    reddit_downloader.download()
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\bdfr\downloader.py", line 45, in download
    self._download_submission(submission)
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\bdfr\downloader.py", line 73, in _download_submission
    content = downloader.find_resources(self.authenticator)
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\bdfr\site_downloaders\youtube.py", line 31, in find_resources
    extension = self.get_video_attributes(self.post.url)['ext']
TypeError: 'NoneType' object is not subscriptable

**Comment by Serene-Arc** [comment]
Fixed with 3fa7bb9 and the switch from youtube-dl, it's barely being maintained if at all.
