### ISSUE TITLE
[BUG] Disabling Youtube module with --disable-module parameter doesn't work

### ISSUE THREAD

**Issue by mbarr564** [aliparlakci/bulk-downloader-for-reddit#527]
## Description
Providing the parameter "--disable-module YoutubeDlFallback" seems to work, but when also providing parameter "--disable-module Youtube", BDFR still attempts to use the Youtube module to unsuccessfully download websites. These modules are causing lots of errors in BDFR output logs, and the YoutubeDlFallback module is currently causing crashes.

This behavior is displayed when BDFR is run from my PowerShell wrapper script:
https://github.com/mbarr564/powershell/blob/master/New-SubredditHTMLArchive.ps1

## Command
python.exe -m bdfr clone c:\bdfr_output\ --subreddit PowerShell --disable-module Youtube

## Environment (please complete the following information):
 - OS: Windows 10
 - Python version: 3.9.7

## Logs
[2021-09-30 23:19:27,629 - bdfr.downloader - DEBUG] - Attempting to download submission mwoxuj
[2021-09-30 23:19:28,438 - bdfr.site_downloaders.youtube - ERROR] - ERROR: Unsupported URL: https://amp.cnn.com/cnn/2021/02/24/politics/cia-diplomats-sonic-attacks-task-force/index.html
Traceback (most recent call last):
  File "C:\Users\micha\AppData\Local\Programs\Python\Python39\lib\site-packages\youtube_dl\YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "C:\Users\micha\AppData\Local\Programs\Python\Python39\lib\site-packages\youtube_dl\YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "C:\Users\micha\AppData\Local\Programs\Python\Python39\lib\site-packages\youtube_dl\extractor\common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "C:\Users\micha\AppData\Local\Programs\Python\Python39\lib\site-packages\youtube_dl\extractor\generic.py", line 3520, in _real_extract
    raise UnsupportedError(url)
youtube_dl.utils.UnsupportedError: Unsupported URL: https://amp.cnn.com/cnn/2021/02/24/politics/cia-diplomats-sonic-attacks-task-force/index.html

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\micha\AppData\Local\Programs\Python\Python39\lib\site-packages\bdfr\site_downloaders\youtube.py", line 69, in get_video_attributes
    result = ydl.extract_info(url, download=False)
  File "C:\Users\micha\AppData\Local\Programs\Python\Python39\lib\site-packages\youtube_dl\YoutubeDL.py", line 808, in extract_info
    return self.__extract_info(url, ie, download, extra_info, process)
  File "C:\Users\micha\AppData\Local\Programs\Python\Python39\lib\site-packages\youtube_dl\YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "C:\Users\micha\AppData\Local\Programs\Python\Python39\lib\site-packages\youtube_dl\YoutubeDL.py", line 847, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "C:\Users\micha\AppData\Local\Programs\Python\Python39\lib\site-packages\youtube_dl\YoutubeDL.py", line 885, in process_ie_result
    return self.extract_info(ie_result['url'],
  File "C:\Users\micha\AppData\Local\Programs\Python\Python39\lib\site-packages\youtube_dl\YoutubeDL.py", line 808, in extract_info
    return self.__extract_info(url, ie, download, extra_info, process)
  File "C:\Users\micha\AppData\Local\Programs\Python\Python39\lib\site-packages\youtube_dl\YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "C:\Users\micha\AppData\Local\Programs\Python\Python39\lib\site-packages\youtube_dl\YoutubeDL.py", line 847, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "C:\Users\micha\AppData\Local\Programs\Python\Python39\lib\site-packages\youtube_dl\YoutubeDL.py", line 885, in process_ie_result
    return self.extract_info(ie_result['url'],
  File "C:\Users\micha\AppData\Local\Programs\Python\Python39\lib\site-packages\youtube_dl\YoutubeDL.py", line 808, in extract_info
    return self.__extract_info(url, ie, download, extra_info, process)
  File "C:\Users\micha\AppData\Local\Programs\Python\Python39\lib\site-packages\youtube_dl\YoutubeDL.py", line 824, in wrapper
    self.report_error(compat_str(e), e.format_traceback())
  File "C:\Users\micha\AppData\Local\Programs\Python\Python39\lib\site-packages\youtube_dl\YoutubeDL.py", line 628, in report_error
    self.trouble(error_message, tb)
  File "C:\Users\micha\AppData\Local\Programs\Python\Python39\lib\site-packages\youtube_dl\YoutubeDL.py", line 598, in trouble
    raise DownloadError(message, exc_info)
youtube_dl.utils.DownloadError: ERROR: Unsupported URL: https://amp.cnn.com/cnn/2021/02/24/politics/cia-diplomats-sonic-attacks-task-force/index.html
[2021-09-30 23:19:28,441 - bdfr.downloader - ERROR] - Could not download submission mwoxuj: No downloader module exists for url https://amp.cnn.com/cnn/2021/02/24/politics/cia-diplomats-sonic-attacks-task-force/index.html
[2021-09-30 23:19:28,441 - bdfr.archive_entry.submission_archive_entry - DEBUG] - Retrieving full comment tree for submission mwoxuj
[2021-09-30 23:19:28,755 - bdfr.archiver - DEBUG] - Writing entry mwoxuj to file in JSON format at C:\Users\micha\Documents\BDFR\JSON\psychotronics\rrab_CIA launches task force to probe invisible attacks on US diplomats and spies_mwoxuj.json
[2021-09-30 23:19:28,756 - bdfr.archiver - INFO] - Record for entry item mwoxuj written to disk

**Comment by Serene-Arc** [comment]
I don't think that's what this is. The error looks like it's occurring before the module is checked against the disabled list. If that's the case then the program is performing as written.

This is more a comment for myself when I get to it so I know where to look. But yeah, if all this is in the log file, then it's performing as intended.

**Comment by Serene-Arc** [comment]
Program is working as intended, those tracebacks are meant to be there so we can troubleshoot youtube-dl if necessary
