### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by nascentt** [aliparlakci/bulk-downloader-for-reddit#534]
- [ X ] I am reporting a bug.
- [ X ] I am running the latest version of BDfR
- [ X ] I have read the [Opening an issue](https://github.com/aliparlakci/bulk-downloader-for-reddit/blob/master/docs/CONTRIBUTING.md#opening-an-issue)
  
## Description
new v2 app doesn't work

bulk-downloader-for-reddit.exe works fine

## Command
```
python -m bdfr download
```

## Environment (please complete the following information):
 - OS: [e.g. Windows 10]
 - Python version: [e.g. 3.9.4]

## Logs
```
Traceback (most recent call last):
  File "C:\Program Files (x86)\Python39-32\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files (x86)\Python39-32\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\nascent\AppData\Roaming\Python\Python39\site-packages\bdfr\__main__.py", line 9, in <module>
    from bdfr.cloner import RedditCloner
  File "C:\Users\nascent\AppData\Roaming\Python\Python39\site-packages\bdfr\cloner.py", line 8, in <module>
    from bdfr.downloader import RedditDownloader
  File "C:\Users\nascent\AppData\Roaming\Python\Python39\site-packages\bdfr\downloader.py", line 19, in <module>
    from bdfr.site_downloaders.download_factory import DownloadFactory
  File "C:\Users\nascent\AppData\Roaming\Python\Python39\site-packages\bdfr\site_downloaders\download_factory.py", line 12, in <module>
    from bdfr.site_downloaders.fallback_downloaders.youtubedl_fallback import YoutubeDlFallback
  File "C:\Users\nascent\AppData\Roaming\Python\Python39\site-packages\bdfr\site_downloaders\fallback_downloaders\youtubedl_fallback.py", line 12, in <module>
    from bdfr.site_downloaders.youtube import Youtube
  File "C:\Users\nascent\AppData\Roaming\Python\Python39\site-packages\bdfr\site_downloaders\youtube.py", line 8, in <module>
    import youtube_dl
  File "C:\Users\nascent\AppData\Roaming\Python\Python39\site-packages\youtube_dl\__init__.py", line 15, in <module>
    from .options import (
  File "C:\Users\nascent\AppData\Roaming\Python\Python39\site-packages\youtube_dl\options.py", line 8, in <module>
    from .downloader.external import list_external_downloaders
  File "C:\Users\nascent\AppData\Roaming\Python\Python39\site-packages\youtube_dl\downloader\__init__.py", line 5, in <module>
    from .hls import HlsFD
  File "C:\Users\nascent\AppData\Roaming\Python\Python39\site-packages\youtube_dl\downloader\hls.py", line 6, in <module>
    from Crypto.Cipher import AES
  File "C:\Users\nascent\AppData\Roaming\Python\Python39\site-packages\Crypto\Cipher\__init__.py", line 27, in <module>
    from Crypto.Cipher._mode_ecb import _create_ecb_cipher
  File "C:\Users\nascent\AppData\Roaming\Python\Python39\site-packages\Crypto\Cipher\_mode_ecb.py", line 35, in <module>
    raw_ecb_lib = load_pycryptodome_raw_lib("Crypto.Cipher._raw_ecb", """
  File "C:\Users\nascent\AppData\Roaming\Python\Python39\site-packages\Crypto\Util\_raw_api.py", line 309, in load_pycryptodome_raw_lib
    raise OSError("Cannot load native module '%s': %s" % (name, ", ".join(attempts)))
OSError: Cannot load native module 'Crypto.Cipher._raw_ecb': Not found '_raw_ecb.cp39-win32.pyd', Cannot load '_raw_ecb.pyd': [WinError 193] %1 is not a valid Win32 application```

**Comment by Serene-Arc** [comment]
This doesn't have anything to do with the BDFR. It's an error thrown by Youtube-DL because you're missing a package, `Crypto` by the look of it. You need to reinstall it, or possibly reinstall Python.

**Comment by nascentt** [comment]
Then you need to update your documentation. 
I followed the instructions on the main page, and it say nothing about installing any packages or anything to do with crypto.
Plus this was working up until a few days ago.

**Comment by aliparlakci** [comment]
We are using youtube-dl python package under the hood. Most probably, they published a new release which has a bug. We will look into it.

**Comment by Serene-Arc** [comment]
@nascentt this has nothing to do with our documentation, your install is broken in some way. Just because it was working until now doesn't mean this isn't the case. The BDFR is calling the youtube-dl module, which is calling another package which is broken in some way. We can't troubleshoot that for you, it's not related to the BDFR at all. Try googling the error and seeing what you get, the only thing we would be able to do is the same thing. It's not related to our code. A quick google I just did said that running `python3 -m pip install pycryptodomex` might fix it.

@aliparlakci we moved away from youtube-dl in the development branch, the BDFR now uses a fork called youtube-dlp. youtube-dl looks like it's dead, pretty much. It's not getting regular enough updates to keep up with site changes.
