### ISSUE TITLE
[BUG] BDFR works without --authenticate flag but exits when I'm trying to use it

### ISSUE THREAD

**Issue by pawelmalak** [aliparlakci/bulk-downloader-for-reddit#545]
- [x] I am reporting a bug.
- [x] I am running the latest version of BDfR
- [x] I have read the [Opening an issue](https://github.com/aliparlakci/bulk-downloader-for-reddit/blob/master/docs/CONTRIBUTING.md#opening-an-issue)
  
## Description
I'm getting [WinError 10013] while using BDFR with `--authenticate` flag. It works fine without it.

## Command
```
python -m bdfr download ./posts --user me --upvoted --file-scheme "{SUBREDDIT}_{TITLE}_{POSTID}" --authenticate -v
```

## Environment (please complete the following information):
 - OS: [Windows 10]
 - Python version: [3.9.5]

## Logs
```
[2021-10-30 02:25:25,085 - bdfr.connector - DEBUG] - Setting maximum download wait time to 120 seconds
[2021-10-30 02:25:25,086 - bdfr.connector - DEBUG] - Setting datetime format string to ISO
[2021-10-30 02:25:25,086 - bdfr.connector - DEBUG] - Disabling the following modules: 
[2021-10-30 02:25:25,086 - bdfr.connector - Level 9] - Created download filter
[2021-10-30 02:25:25,086 - bdfr.connector - Level 9] - Created time filter
[2021-10-30 02:25:25,087 - bdfr.connector - Level 9] - Created sort filter
[2021-10-30 02:25:25,087 - bdfr.connector - Level 9] - Create file name formatter
[2021-10-30 02:25:25,087 - bdfr.connector - DEBUG] - Using authenticated Reddit instance
[2021-10-30 02:25:25,087 - bdfr.connector - Level 9] - Commencing OAuth2 authentication
[2021-10-30 02:25:25,293 - bdfr.oauth2 - WARNING] - Authentication action required before the program can proceed
[2021-10-30 02:25:25,293 - bdfr.oauth2 - WARNING] - Authenticate at https://www.reddit.com/api/v1/authorize?{...}
[2021-10-30 02:25:25,293 - root - ERROR] - Downloader exited unexpectedly
Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\site-packages\bdfr\__main__.py", line 81, in cli_download
    reddit_downloader = RedditDownloader(config)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\site-packages\bdfr\downloader.py", line 38, in __init__
    super(RedditDownloader, self).__init__(args)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\site-packages\bdfr\connector.py", line 57, in __init__
    self._setup_internal_objects()
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\site-packages\bdfr\connector.py", line 79, in _setup_internal_objects
    self.create_reddit_instance()
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\site-packages\bdfr\connector.py", line 132, in create_reddit_instance
    token = oauth2_authenticator.retrieve_new_token()
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\site-packages\bdfr\oauth2.py", line 53, in retrieve_new_token
    client = self.receive_connection()
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\site-packages\bdfr\oauth2.py", line 73, in receive_connection
    server.bind(('0.0.0.0', 7634))
OSError: [WinError 10013] An attempt was made to access a socket in a way forbidden by its access permissions
```

**Comment by Serene-Arc** [comment]
What happens when you run the script as administrator?

**Comment by pawelmalak** [comment]
I had to restart whole machine and then run it normally (non-admin). Windows defender asked then for access to the internet and now it working correctly. Thanks
