### ISSUE TITLE
[BUG] unexpected traceback

### ISSUE THREAD

**Issue by jrwren** [aliparlakci/bulk-downloader-for-reddit#548]
- [X ] I am reporting a bug.
- [I think so ] I am running the latest version of BDfR
- [X ] I have read the [Opening an issue](https://github.com/aliparlakci/bulk-downloader-for-reddit/blob/master/docs/CONTRIBUTING.md#opening-an-issue)
  
## Description
unexpected traceback

Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/stor/jrwren/po/r/lib/python3.9/site-packages/bdfr/__main__.py", line 153, in <module>
    cli()
  File "/stor/jrwren/po/r/lib/python3.9/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/stor/jrwren/po/r/lib/python3.9/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/stor/jrwren/po/r/lib/python3.9/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/stor/jrwren/po/r/lib/python3.9/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/stor/jrwren/po/r/lib/python3.9/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/stor/jrwren/po/r/lib/python3.9/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/stor/jrwren/po/r/lib/python3.9/site-packages/bdfr/__main__.py", line 82, in cli_download
    reddit_downloader.download()
  File "/stor/jrwren/po/r/lib/python3.9/site-packages/bdfr/downloader.py", line 45, in download
    self._download_submission(submission)
  File "/stor/jrwren/po/r/lib/python3.9/site-packages/bdfr/downloader.py", line 73, in _download_submission
    content = downloader.find_resources(self.authenticator)
  File "/stor/jrwren/po/r/lib/python3.9/site-packages/bdfr/site_downloaders/fallback_downloaders/youtubedl_fallback.py", line 26, in find_resources
    super().get_video_attributes(self.post.url)['ext'],
KeyError: 'ext'

## Command
```
bin/python -m bdfr download peanutgainzel --user peanutgainzel  -t year --authenticate --no-dupes --submitted --folder-scheme '' --file-scheme '{TITLE}_{SUBREDDIT}_{POSTID}'
```

## Environment (please complete the following information):
 - OS: Linux
 - Python version: 3.9.7

## Logs
```
I do not know where to find the log.
```

**Comment by zemzale** [comment]
This is the same issue as in #560
