### ISSUE TITLE
[BUG] Python errors after a few posts are downloaded, KeyError:'ext'

### ISSUE THREAD

**Issue by c0mplexx92** [aliparlakci/bulk-downloader-for-reddit#560]
- [x ] I am reporting a bug.
- [x ] I am running the latest version of BDfR
- [ x] I have read the [Opening an issue](https://github.com/aliparlakci/bulk-downloader-for-reddit/blob/master/docs/CONTRIBUTING.md#opening-an-issue)
  
## Description
It seems to download a few posts and then gives the errors(?), it worked fine yesterday and unless i'm misremembering I didn't change anything. I've tried reinstalling both Python and BDFR but the issue persists
## Command
```
py -m bdfr download F:\Downloads\Here --user c0mplexx -m aesthethic --sort top -t day

this happens with python3 instead of py as well
```

## Environment (please complete the following information):
 - OS: Windows 10
 - Python version: 3.10

## Logs
```
Traceback (most recent call last):
  File "C:\Users\thene\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\thene\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "F:\Documents\bulk-downloader-for-reddit-2.4.2\bdfr\__main__.py", line 153, in <module>
    cli()
  File "C:\Users\thene\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\thene\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "C:\Users\thene\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\thene\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\thene\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\thene\AppData\Local\Programs\Python\Python310\lib\site-packages\click\decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "F:\Documents\bulk-downloader-for-reddit-2.4.2\bdfr\__main__.py", line 82, in cli_download
    reddit_downloader.download()
  File "F:\Documents\bulk-downloader-for-reddit-2.4.2\bdfr\downloader.py", line 45, in download
    self._download_submission(submission)
  File "F:\Documents\bulk-downloader-for-reddit-2.4.2\bdfr\downloader.py", line 73, in _download_submission
    content = downloader.find_resources(self.authenticator)
  File "F:\Documents\bulk-downloader-for-reddit-2.4.2\bdfr\site_downloaders\fallback_downloaders\youtubedl_fallback.py", line 26, in find_resources
    super().get_video_attributes(self.post.url)['ext'],
KeyError: 'ext'
```

**Comment by zemzale** [comment]
I looked into this and the problem, in this case, is trying to get this https://www.reddit.com/r/outrun/comments/qwrefa/miles_matrix_la_boum_80s_electro_breakdance_2021/

I don't know the reasons why and how this stuff works, but I assume this fallback is used for videos, but here `get_video_attributes` doesn't return the `ext` key. 

To remove the KeyError I just switched out `["ext"]` on `bdfr\site_downloaders\fallback_downloaders\youtubedl_fallback.py", line 26` with `.get("ext")`. 

This didn't download the file, so I am not sure what else can be done here. If this kind of fix is valid I can open up a PR.
