### ISSUE TITLE
[BUG] NoneType error with submission.author having no name attribute

### ISSUE THREAD

**Issue by wonderingwombat** [aliparlakci/bulk-downloader-for-reddit#564]
- [x] I am reporting a bug.
- [x] I am running the latest version of BDfR
- [x] I have read the [Opening an issue](https://github.com/aliparlakci/bulk-downloader-for-reddit/blob/master/docs/CONTRIBUTING.md#opening-an-issue)
  
## Description
I encountered an error when trying to download the saved posts under my reddit account. This may be related to something specific in in my saved posts. Changing line `54` to:
```
elif submission.author and submission.author.name in self.args.ignore_user:
```
in `def _download_submission` of `downloads.py` seems to resolve the issue.

## Command
```
python3 -m bdfr download Media_Saved --authenticate --saved --user me
```

## Environment:
 - OS: [OSX 10.4.6]
 - Python version: [3.9.5]

## Logs
```
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/bdfr/__main__.py", line 154, in <module>
    cli()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/click/core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/bdfr/__main__.py", line 83, in cli_download
    reddit_downloader.download()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/bdfr/downloader.py", line 45, in download
    self._download_submission(submission)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/bdfr/downloader.py", line 54, in _download_submission
    elif submission.author.name and submission.author.name in self.args.ignore_user:
AttributeError: 'NoneType' object has no attribute 'name'
```

**Comment by Serene-Arc** [comment]
Hi, can you please provide the actual logs that relate to this bug, or at least the submission ID that caused this error.

**Comment by wonderingwombat** [comment]
Hi Serene-Arc,

The submission IDs seem the be one of the following: 

- hkqawhq
- hlur4o5

The second one looks like it may have been deleted: https://api.pushshift.io/reddit/search/comment/?ids=hlur4o5

Here is the last part of the log file: 
```
...
[2021-11-28 17:41:29,782 - bdfr.downloader - INFO] - Downloaded submission r14mzy from LifeProTips
[2021-11-28 17:41:29,783 - bdfr.downloader - DEBUG] - Attempting to download submission qudpd8
[2021-11-28 17:41:29,783 - bdfr.downloader - DEBUG] - Using SelfPost with url https://www.reddit.com/r/AskMenOver30/comments/qudpd8/why_are_we_never_depicted_in_books_and_movies/
[2021-11-28 17:41:30,781 - bdfr.downloader - DEBUG] - File /Users/wonderingwombat/bdfr/Media_Saved/AskMenOver30/jcano_Why are we never depicted in books and movies chasing our dreams or figuring out what to do with our lives?_qudpd8.txt from submission qudpd8 already exists, continuing
[2021-11-28 17:41:30,782 - bdfr.downloader - INFO] - Downloaded submission qudpd8 from AskMenOver30
[2021-11-28 17:41:30,782 - bdfr.downloader - WARNING] - hkqawhq is not a submission
[2021-11-28 17:41:30,783 - bdfr.downloader - WARNING] - hlur4o5 is not a submission
[2021-11-28 17:41:30,783 - root - ERROR] - Downloader exited unexpectedly
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/bdfr/__main__.py", line 83, in cli_download
    reddit_downloader.download()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/bdfr/downloader.py", line 45, in download
    self._download_submission(submission)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/bdfr/downloader.py", line 54, in _download_submission
    elif submission.author.name in self.args.ignore_user:
AttributeError: 'NoneType' object has no attribute 'name'

```

**Comment by wonderingwombat** [comment]
Awesome, thank you!
