### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by DaBlincx** [aliparlakci/bulk-downloader-for-reddit#638]
- [x] I am reporting a bug.
- [x] I am running the latest version of BDfR
- [x] I have read the [Opening an issue](https://github.com/aliparlakci/bulk-downloader-for-reddit/blob/master/docs/CONTRIBUTING.md#opening-an-issue)
  
## Description
When I try downloading any subreddit, it says `configparser.NoOptionError: No option 'client_id' in section: 'DEFAULT'`.

## Command
```
python -m bdfr download . --no-dupes --sort=new --subreddit memes
```

## Environment :
 - OS: Windows 10
 - Python version: 3.10.4

## Logs
```
[2022-06-16 17:01:35,772 - bdfr.connector - DEBUG] - Setting maximum download wait time to 120 seconds
[2022-06-16 17:01:35,772 - bdfr.connector - DEBUG] - Setting datetime format string to ISO
[2022-06-16 17:01:35,773 - bdfr.connector - DEBUG] - Disabling the following modules: 
[2022-06-16 17:01:35,773 - bdfr.connector - Level 9] - Created download filter
[2022-06-16 17:01:35,773 - bdfr.connector - Level 9] - Created time filter
[2022-06-16 17:01:35,773 - bdfr.connector - Level 9] - Created sort filter
[2022-06-16 17:01:35,774 - bdfr.connector - Level 9] - Create file name formatter
[2022-06-16 17:01:35,774 - bdfr.connector - DEBUG] - Using unauthenticated Reddit instance
[2022-06-16 17:01:35,774 - root - ERROR] - Downloader exited unexpectedly
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\configparser.py", line 790, in get
    value = d[option]
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\collections\__init__.py", line 986, in __getitem__
    return self.__missing__(key)            # support subclasses that define __missing__
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\collections\__init__.py", line 978, in __missing__
    raise KeyError(key)
KeyError: 'client_id'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\user\AppData\Roaming\Python\Python310\site-packages\bdfr\__main__.py", line 82, in cli_download
    reddit_downloader = RedditDownloader(config)
  File "C:\Users\user\AppData\Roaming\Python\Python310\site-packages\bdfr\downloader.py", line 38, in __init__
    super(RedditDownloader, self).__init__(args)
  File "C:\Users\user\AppData\Roaming\Python\Python310\site-packages\bdfr\connector.py", line 57, in __init__
    self._setup_internal_objects()
  File "C:\Users\user\AppData\Roaming\Python\Python310\site-packages\bdfr\connector.py", line 79, in _setup_internal_objects
    self.create_reddit_instance()
  File "C:\Users\user\AppData\Roaming\Python\Python310\site-packages\bdfr\connector.py", line 149, in create_reddit_instance
    client_id=self.cfg_parser.get('DEFAULT', 'client_id'),
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\configparser.py", line 793, in get
    raise NoOptionError(option, section)
configparser.NoOptionError: No option 'client_id' in section: 'DEFAULT'
```

**Comment by Serene-Arc** [comment]
This is due to missing lines in the configuration file. Can you confirm it exists at the location described in the README?

**Comment by DaBlincx** [comment]
the configuration file exists bur its empty.

i solved the problem by copying the the values from the default_config.cfg in the bdfr module folder into that connector.py file
