### ISSUE TITLE
TypeError: 'type' object is not subscriptable

### ISSUE THREAD

**Issue by Krebrov001** [aliparlakci/bulk-downloader-for-reddit#678]
- [X] I am reporting a bug.
- [X] I am running the latest version of BDfR
- [X] I have read the [Opening an issue](https://github.com/aliparlakci/bulk-downloader-for-reddit/blob/master/docs/CONTRIBUTING.md#opening-an-issue)
  
## Description
I tried to run the command below, which was from the markdown file.

This is the output:

```
Traceback (most recent call last):
  File "/home/konstantin/miniconda3/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/konstantin/miniconda3/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/konstantin/miniconda3/lib/python3.7/site-packages/bdfr/__main__.py", line 8, in <module>
    from bdfr.archiver import Archiver
  File "/home/konstantin/miniconda3/lib/python3.7/site-packages/bdfr/archiver.py", line 15, in <module>
    from bdfr.archive_entry.submission_archive_entry import SubmissionArchiveEntry
  File "/home/konstantin/miniconda3/lib/python3.7/site-packages/bdfr/archive_entry/submission_archive_entry.py", line 13, in <module>
    class SubmissionArchiveEntry(BaseArchiveEntry):
  File "/home/konstantin/miniconda3/lib/python3.7/site-packages/bdfr/archive_entry/submission_archive_entry.py", line 41, in SubmissionArchiveEntry
    def _get_comments(self) -> list[dict]:
TypeError: 'type' object is not subscriptable
```

## Command
```
python3 -m bdfr download ./path/to/output --subreddit Python -L 10
```

## Environment (please complete the following information):
 - OS: **Ubuntu 18.04 bionic [Ubuntu on Windows 10]**
 - Python version: **Python 3.7.6**

**Comment by Serene-Arc** [comment]
You do not meet the minimum python version requirement, it is 3.9.
