### ISSUE TITLE
i'm getting this error msg (using ubuntu, and yes I did update)

### ISSUE THREAD

**Issue by flynnsharwood** [aliparlakci/bulk-downloader-for-reddit#688]
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/mnt/c/Users/harsh/redditbulkdownload/bdfr/__main__.py", line 8, in <module>
    from bdfr.archiver import Archiver
  File "/mnt/c/Users/harsh/redditbulkdownload/bdfr/archiver.py", line 15, in <module>
    from bdfr.archive_entry.submission_archive_entry import SubmissionArchiveEntry
  File "/mnt/c/Users/harsh/redditbulkdownload/bdfr/archive_entry/submission_archive_entry.py", line 13, in <module>
    class SubmissionArchiveEntry(BaseArchiveEntry):
  File "/mnt/c/Users/harsh/redditbulkdownload/bdfr/archive_entry/submission_archive_entry.py", line 45, in SubmissionArchiveEntry
    def _get_comments(self) -> list[dict]:
TypeError: 'type' object is not subscriptable

**Comment by Serene-Arc** [comment]
You haven't updated python. Minimum version is python 3.9 and you are using python 3.8, as clearly described in the error message.
