### ISSUE TITLE
No longer working

### ISSUE THREAD

**Issue by Wolfeman0101** [aliparlakci/bulk-downloader-for-reddit#712]
Not sure what changed but all of the sudden BDFR isn't working.  This is what I'm getting.

`Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\bkwol\AppData\Local\Programs\Python\Python311\Lib\site-packages\bdfr\__main__.py", line 162, in <module>
    cli()
  File "C:\Users\bkwol\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bkwol\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "C:\Users\bkwol\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bkwol\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bkwol\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bkwol\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bkwol\AppData\Local\Programs\Python\Python311\Lib\site-packages\bdfr\__main__.py", line 90, in cli_download
    reddit_downloader = RedditDownloader(config)
                        ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bkwol\AppData\Local\Programs\Python\Python311\Lib\site-packages\bdfr\downloader.py", line 39, in __init__
    super(RedditDownloader, self).__init__(args)
  File "C:\Users\bkwol\AppData\Local\Programs\Python\Python311\Lib\site-packages\bdfr\connector.py", line 57, in __init__
    self._setup_internal_objects()
  File "C:\Users\bkwol\AppData\Local\Programs\Python\Python311\Lib\site-packages\bdfr\connector.py", line 63, in _setup_internal_objects
    self.load_config()
  File "C:\Users\bkwol\AppData\Local\Programs\Python\Python311\Lib\site-packages\bdfr\connector.py", line 198, in load_config
    self.cfg_parser.read(self.config_location)
  File "C:\Users\bkwol\AppData\Local\Programs\Python\Python311\Lib\configparser.py", line 712, in read
    self._read(fp, filename)
  File "C:\Users\bkwol\AppData\Local\Programs\Python\Python311\Lib\configparser.py", line 1100, in _read
    raise MissingSectionHeaderError(fpname, lineno, line)
configparser.MissingSectionHeaderError: File contains no section headers.
file: WindowsPath('C:/Users/bkwol/AppData/Local/BDFR/bdfr/default_config.cfg'), line: 1
'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'
`

**Comment by Serene-Arc** [comment]
Your configuration file has been corrupted. You'll have to recreate it and reauthenticate.
