### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by trainzkid** [aliparlakci/bulk-downloader-for-reddit#756]
- [✓] I am reporting a bug.
- [✓] I am running the latest version of BDfR
- [✓] I have read the [Opening an issue](https://github.com/aliparlakci/bulk-downloader-for-reddit/blob/master/docs/CONTRIBUTING.md#opening-an-issue)

## Description

- BDFR hangs indefinitely if [this Reddit post (zaq5ab)](https://www.reddit.com/r/cpp/comments/zaq5ab/c_template_parlor_tricks_using_a_type_before_it/) is part of what I request it to download.
- If I remove that specific post from whatever I request it to download (in my case, my reddit saves), it runs without any issues. As soon as I add that post back, it gets stuck.
- This occurs on both versions 2.6.0-2 (newest non-git version from the AUR) and 2.6.1.r38.g00c4307-1 (newest git version from the AUR).
- This issue began occurring after a recent sysupgrade and the offending post has already been saved to my device from a previous run of BDFR, so I'm assuming this wasn't a problem in previous versions (2.5.2-2 was last working version according to my logs), though I've yet to downgrade and confirm.

## Command

```text
python3 -m bdfr clone /home/ryan/reddit-saves -f yaml --user me --saved --authenticate
```

## Environment

- OS: Arch Linux (linux-zen 6.1.5.zen2-1)
- Python version: python 3.10.9-1

## Logs

```text
[2023-01-19 16:11:29,325 - bdfr.connector - DEBUG] - Disabling the following modules: 
[2023-01-19 16:11:29,325 - bdfr.connector - Level 9] - Created download filter
[2023-01-19 16:11:29,325 - bdfr.connector - Level 9] - Created time filter
[2023-01-19 16:11:29,325 - bdfr.connector - Level 9] - Created sort filter
[2023-01-19 16:11:29,328 - bdfr.connector - Level 9] - Create file name formatter
[2023-01-19 16:11:29,328 - bdfr.connector - DEBUG] - Using authenticated Reddit instance
[2023-01-19 16:11:29,433 - bdfr.oauth2 - Level 9] - Loaded OAuth2 token for authoriser
[2023-01-19 16:11:29,759 - bdfr.oauth2 - Level 9] - Written OAuth2 token from authoriser to /home/ryan/.config/bdfr/default_config.cfg
[2023-01-19 16:11:29,937 - bdfr.connector - Level 9] - Resolved user to Trainzkid
[2023-01-19 16:11:29,937 - bdfr.connector - Level 9] - Created site authenticator
[2023-01-19 16:11:29,937 - bdfr.connector - Level 9] - Retrieved subreddits
[2023-01-19 16:11:29,937 - bdfr.connector - Level 9] - Retrieved multireddits
[2023-01-19 16:11:30,188 - bdfr.connector - DEBUG] - Retrieving saved posts of user Trainzkid
[2023-01-19 16:11:30,189 - bdfr.connector - Level 9] - Retrieved user data
[2023-01-19 16:11:30,189 - bdfr.connector - Level 9] - Retrieved submissions for given links
[2023-01-19 16:11:31,999 - bdfr.downloader - DEBUG] - Attempting to download submission zaq5ab

```

**Comment by OMEGARAZER** [comment]
So taking a look into this it looks like the link is getting caught up [here](https://github.com/aliparlakci/bulk-downloader-for-reddit/blob/development/bdfr/site_downloaders/download_factory.py#L58) so yt-dlp is getting stuck trying to decide if there's anything there for it.

```
Traceback (most recent call last):
  File "./test.py", line 48, in <module>

  File "/bulk-downloader-for-reddit/bdfr/site_downloaders/fallback_downloaders/ytdlp_fallback.py", line 33, in can_handle_link
    attributes = YtdlpFallback.get_video_attributes(url)
  File "/bulk-downloader-for-reddit/bdfr/site_downloaders/youtube.py", line 80, in get_video_attributes
    result = Youtube.get_video_data(url)
  File "/bulk-downloader-for-reddit/bdfr/site_downloaders/youtube.py", line 72, in get_video_data
    result = ydl.extract_info(url, download=False)
  File "/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1491, in extract_info
    return self.__extract_info(url, self.get_info_extractor(key), download, extra_info, process)
  File "/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1502, in wrapper
    return func(self, *args, **kwargs)
  File "/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1599, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1678, in process_ie_result
    return self.extract_info(
  File "/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1491, in extract_info
    return self.__extract_info(url, self.get_info_extractor(key), download, extra_info, process)
  File "/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1502, in wrapper
    return func(self, *args, **kwargs)
  File "/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1599, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1678, in process_ie_result
    return self.extract_info(
  File "/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1491, in extract_info
    return self.__extract_info(url, self.get_info_extractor(key), download, extra_info, process)
  File "/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1502, in wrapper
    return func(self, *args, **kwargs)
  File "/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1578, in __extract_info
    ie_result = ie.extract(url)
  File "/lib/python3.10/site-packages/yt_dlp/extractor/common.py", line 680, in extract
    ie_result = self._real_extract(url)
  File "/lib/python3.10/site-packages/yt_dlp/extractor/generic.py", line 2518, in _real_extract
    embeds = list(self._extract_embeds(original_url, webpage, urlh=full_response, info_dict=info_dict))
  File "/lib/python3.10/site-packages/yt_dlp/extractor/generic.py", line 2639, in _extract_embeds
    found = self._search_regex((
  File "/lib/python3.10/site-packages/yt_dlp/extractor/common.py", line 1211, in _search_regex
    mobj = re.search(p, string, flags)
  File "/usr/lib/python3.10/re.py", line 200, in search
    return _compile(pattern, flags).search(string)
KeyboardInterrupt
```

As a workaround, you can add this just above the line I mentioned above so that it doesn't hang.

```
elif re.match(r"devblogs\.microsoft\.com", sanitised_url):
    raise NotADownloadableLinkError(f"No downloader module exists for url {url}")
```

Of course, that will stop anything on the devblogs.microsoft.com subdomain from being downloaded (if there is anything to be downloaded there).

**Comment by Serene-Arc** [comment]
Rather than modify the BDFR code, is this an issue with yt-dlp that is fixed with later versions? Might be simpler/more comprehensive to just bump the version number in the requirements.

**Comment by OMEGARAZER** [comment]
It's not, I tested with the latest version.

**Comment by trainzkid** [comment]
That specific Reddit save was found on my disk from a previous run of BDFR so I think a better workaround would likely be to downgrade either BDFR or yt-dlp (depending on who's the culprit) to whatever version worked previously.

Since it was just the one save that hung BDFR and I had already saved it to disk, I just unsaved it for now.

If this is truly an issue with yt-dlp and not BDFR, has anyone opened up an issue with yt-dlp?
