### ISSUE TITLE
[BUG] Crash YAML File underscore in skip_subreddit

### ISSUE THREAD

**Issue by philippdevo** [aliparlakci/bulk-downloader-for-reddit#862]
- [x ] I am reporting a bug.
- [x ] I am running the latest version of BDfR
- [x ] I have read the [Opening an issue](https://github.com/aliparlakci/bulk-downloader-for-reddit/blob/master/docs/CONTRIBUTING.md#opening-an-issue)

## Description

BDFR crashes if there is a underscore in the yaml file under skip_subreddit:

## Command

D:\RedditBdFrDownloader\RedditBdFrDownloader\bin\Debug\net7.0-windows>bdfr download "D:\xoxlittlefoot" --user xoxlittlefoot --submitted --exclude-id-file "D:\xoxlittlefoot\bdfrDownloadedIds.txt" --log "D:\Logs\Log-2023-5-23-xoxlittlefoot.txt" --opts "D:\xoxlittlefoot\xoxlittlefoot.yaml"
```

## Environment (please complete the following information)

Windows 11
Python 3.11.3

## Logs

file_scheme: "{REDDITOR}_{DATE}_{TITLE}_{POSTID}"
limit: 800
no_dupes: false
make_hard_links: true
search_existing: true
skip_domain:
- erome.com
- onlyfans.com
- pornhubpremium.com
- gfycat.com
- loyalfans.com
- tumblr.com
- videobam.com
- erosshare.com
- twitch.tv
- fansly.com
- streamable.com
- giphy.com
- videobam.com
disable_module:
- Erome
skip_subreddit:
- 18_19
- AdorableNudes
- AskReddit
- B_Cups


[2023-05-23 11:13:17,037 - bdfr.connector - DEBUG] - Disabling the following modules: erome
[2023-05-23 11:13:17,038 - bdfr.connector - Level 9] - Created download filter
[2023-05-23 11:13:17,038 - bdfr.connector - Level 9] - Created time filter
[2023-05-23 11:13:17,038 - bdfr.connector - Level 9] - Created sort filter
[2023-05-23 11:13:17,066 - bdfr.connector - Level 9] - Create file name formatter
[2023-05-23 11:13:17,067 - bdfr.connector - DEBUG] - Using unauthenticated Reddit instance
[2023-05-23 11:13:17,068 - bdfr.connector - Level 9] - Created site authenticator
[2023-05-23 11:13:17,068 - root - ERROR] - Downloader exited unexpectedly
Traceback (most recent call last):
  File "C:\Users\uttga\AppData\Local\Programs\Python\Python311\Lib\site-packages\bdfr\__main__.py", line 117, in cli_download
    reddit_downloader = RedditDownloader(config, [stream])
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\uttga\AppData\Local\Programs\Python\Python311\Lib\site-packages\bdfr\downloader.py", line 41, in __init__
    super(RedditDownloader, self).__init__(args, logging_handlers)
  File "C:\Users\uttga\AppData\Local\Programs\Python\Python311\Lib\site-packages\bdfr\connector.py", line 63, in __init__
    self._setup_internal_objects()
  File "C:\Users\uttga\AppData\Local\Programs\Python\Python311\Lib\site-packages\bdfr\connector.py", line 94, in _setup_internal_objects
    self.args.skip_subreddit = self.split_args_input(self.args.skip_subreddit)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\uttga\AppData\Local\Programs\Python\Python311\Lib\site-packages\bdfr\connector.py", line 252, in split_args_input
    results = re.split(split_pattern, entry)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\uttga\AppData\Local\Programs\Python\Python311\Lib\re\__init__.py", line 206, in split
    return _compile(pattern, flags).split(string, maxsplit)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: expected string or bytes-like object, got 'int'

**Comment by philippdevo** [comment]
It is only, when the phrase is numeric without the "_", like in 18_19
That is a standard issue from yaml.
